import { webgencyDemos } from './webgencyDemos';
// Local-only visual specimens. Never persisted to an Event or publication.
const content = { primary_locale: 'en', story_enabled: false, gift_registry_enabled: true, gift_registry_intro: 'Your love, laughter and presence are all we could wish for on our special day. For those who wish, a wedding list is available', ending_enabled: true };
const event = { event_type: 'Wedding', main_date: 'November 11, 2027', start_time: '6:00 PM', timezone: 'Asia/Beirut', dress_code: 'Formal', rsvp_deadline: 'October 10, 2027', description: 'Therefore what God has joined together, let no one separate' };
export const referenceDemos: any[] = [
    { template: { component_key: 'romantic-floral' }, settings: {}, reference_demo: { countdown_at: '2027-11-11T18:00:00Z', families: ['Yazbek', 'Smith'] }, content, gift_methods: [{ label: 'Bank Account', details: 'DEMO 0000 0000' }, { label: 'Whish Money', details: 'DEMO 000000' }], event: { ...event, title: 'Jack & Stephanie', host_name: 'Jack', second_host_name: 'Stephanie', activities: [{ activity_type: 'meeting_point', title: "Groom’s side", venue: 'Manhattan', start_time: '' }, { activity_type: 'meeting_point', title: "Bride’s side", venue: 'The Plaza Hotel', start_time: '' }, { activity_type: 'ceremony', title: 'Ceremony', venue: 'Saint Rits', start_time: '6:00 PM' }, { activity_type: 'celebration', title: 'Celebration', venue: 'Country Lodge', start_time: '8:00 PM' }] } },
    { template: { component_key: 'editorial-luxury' }, settings: {}, reference_demo: { countdown_at: '2027-06-10T17:00:00Z', families: ['Khoury','Obeid'] }, content: { ...content }, gift_methods: [{label:'Bank Account',details:'IBAN: DEMO 00000000'}], event: { ...event, main_date:'June 10, 2027',start_time:'5:00 PM',rsvp_deadline:'May 10, 2027',title: 'Justin & Maya', host_name: 'Justin', second_host_name: 'Maya', activities: [{activity_type:'meeting_point',title:'Groom House',venue:'Zouk mikael',location_url:'https://maps.app.goo.gl/ehQz2y8nzZNAVJY47'},{activity_type:'meeting_point',title:'Bride House',venue:'Cosmopolitan Hotel',location_url:'https://maps.app.goo.gl/gNXSsz6QrXMYsd1g8'},{activity_type:'ceremony',title:'Wedding Ceremony',venue:'Saint George Church',start_time:'05:00 PM',address:'Beirut, Lebanon',location_url:'https://maps.google.com/maps?q=Saint+George+Church+Beirut+Lebanon'},{activity_type:'celebration',title:'The Celebration',venue:'Country Lodge',start_time:'06:00 PM',address:'Bsalim, Lebanon',location_url:'https://maps.google.com/maps?q=Country+Lodge+Bsalim+Lebanon'}] } },
    { template: { component_key: 'modern-cinematic' }, settings: {}, reference_demo: {countdown_at: '2026-10-10T18:00:00Z', families:['Khattar','Dayeh']}, content: { ...content }, gift_methods: [{label:'Commercial Bank of Dubai',details:'IBAN: DEMO 00000000'},{label:'Whish Money',details:'DEMO 000000'}], event: { ...event, main_date:'October 10, 2026',rsvp_deadline:'September 9, 2026',title: 'Joseph & Sarah', host_name: 'Joseph', second_host_name: 'Sarah', activities: [{activity_type:'meeting_point',title:'Groom house',venue:'zalka',start_time:'3:00 PM'},{activity_type:'meeting_point',title:'Bride house',venue:'Fanar',start_time:'3:00 PM'},{activity_type:'ceremony',title:'Wedding Ceremony',venue:'Our Lady of Harissa',start_time:'6:00 PM'},{activity_type:'celebration',title:'The Celebration',venue:"L'Heritage Venue",start_time:'8:00 PM'},{activity_type:'other',title:'Cake Cutting',start_time:'12:00 PM'}] } },
];

referenceDemos.push({
    template: { component_key: 'royal-plum' }, settings: {},
    reference_demo: { families: ['Khoury', 'Obeid'] },
    content: { ...content, story_enabled: true, story_heading: 'Our Story', story_body: 'Their story began with a simple hello that turned into something unforgettable.Through laughter, adventures, and quiet moments, their love grew stronger.Together, they found a home in each other and dreamed of a beautiful future.Now, they begin their greatest chapter yet forever, side by side.' },
    gift_methods: [{ label: 'Bank Account', details: 'IBAN: DEMO 00000000' }, { label: 'Whish Money', details: 'DEMO 000000' }],
    event: { ...event, title: 'Anthony & Tina', host_name: 'Anthony', second_host_name: 'Tina', main_date: 'October 10, 2027', start_time: '8:00 PM', venue: 'Byblos Palace', rsvp_deadline: 'September 9, 2027', activities: [
        { activity_type: 'meeting_point', title: "Groom's side", venue: 'Jouret El Ballou', location_url: 'https://www.google.com/maps/search/?api=1&query=Jouret%20El%20Ballou' },
        { activity_type: 'meeting_point', title: "Bride's side", venue: 'Ain Saade', location_url: 'https://www.google.com/maps/search/?api=1&query=Ain%20Saade' },
        { activity_type: 'ceremony', title: 'Wedding Ceremony', venue: 'Saint Rita', start_time: '6:00 PM', location_url: 'https://www.google.com/maps/search/?api=1&query=Saint%20Rita%20%20-%206%3A00%20PM' },
        { activity_type: 'celebration', title: 'A Celebration of Love', venue: 'Byblos Palace', start_time: '8:00 PM', location_url: 'https://www.google.com/maps/search/?api=1&query=Byblos%20Palace%20-%208%3A00%20PM' },
    ] },
});

referenceDemos.push(...webgencyDemos);
