<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InvitationPreviewRenderer from '@/Components/InvitationPreviewRenderer.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props = defineProps<{ event: any; templates: any[]; overrides: any; resolvedSettings: any; sectionKeys: string[]; headingFonts: string[]; bodyFonts: string[]; alignments: string[]; layoutVariants: string[]; parties: any[]; canManage: boolean; previewInvitation: any }>();
const sectionLabels: Record<string, string> = { hero: 'Hero / introduction', hosts: 'Hosts', main_date: 'Main date', schedule: 'Schedule', location: 'Venue / location', guest_information: 'Guest information', dress_code: 'Dress code', accommodation: 'Accommodation', rsvp: 'RSVP' };
const form = useForm({ template_id: props.event.template_id || '', settings: { primary_color: props.overrides.primary_color || '', secondary_color: props.overrides.secondary_color || '', heading_font: props.overrides.heading_font || '', body_font: props.overrides.body_font || '', text_alignment: props.overrides.text_alignment || '', layout_variant: props.overrides.layout_variant || '', sections: Object.fromEntries(props.sectionKeys.map((key) => [key, props.overrides.sections?.[key] === true ? 'show' : props.overrides.sections?.[key] === false ? 'hide' : ''])) } });
const previewPartyId = ref('');
const selectedTemplate = computed(() => props.templates.find((template) => template.id === Number(form.template_id)) || props.event.template);
const previewInvitation = computed(() => ({ ...props.previewInvitation, template: selectedTemplate.value ? { name: selectedTemplate.value.name, component_key: selectedTemplate.value.component_key, is_active: selectedTemplate.value.is_active } : null, settings: props.resolvedSettings, party_name: previewPartyId.value ? props.parties.find((party) => party.id === Number(previewPartyId.value))?.name : null }));
const submit = () => form.transform((data) => ({ template_id: data.template_id || null, settings: { primary_color: data.settings.primary_color || undefined, secondary_color: data.settings.secondary_color || undefined, heading_font: data.settings.heading_font || undefined, body_font: data.settings.body_font || undefined, text_alignment: data.settings.text_alignment || undefined, layout_variant: data.settings.layout_variant || undefined, sections: Object.fromEntries(Object.entries(data.settings.sections).filter(([, value]) => value !== '').map(([key, value]) => [key, value === 'show'])) } })).put(route('events.invitation.update', props.event.id));
</script>

<template>
    <Head :title="`${event.title} Invitation`" />
    <AuthenticatedLayout>
        <template #header><div class="flex items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">Invitation</h2><p class="text-sm text-gray-600">Presentation settings only; Event, guest, RSVP, and payment data are unchanged.</p></div><Link :href="route('events.show', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">Back to Event</Link></div></template>
        <div class="mx-auto grid max-w-6xl gap-6 p-6 lg:grid-cols-2">
            <form v-if="canManage" class="space-y-5 rounded bg-white p-6 shadow" @submit.prevent="submit">
                <div><label class="block text-sm font-medium">Selected template</label><select v-model="form.template_id" class="mt-1 w-full rounded border-gray-300"><option value="">No template selected</option><option v-for="template in templates" :key="template.id" :value="template.id">{{ template.name }}{{ template.is_active ? '' : ' (inactive — retained assignment)' }}</option></select><p v-if="event.template && !event.template.is_active" class="mt-2 text-sm text-amber-700">The assigned template is inactive. It remains viewable but cannot be newly selected for another Event.</p><InputError :message="form.errors.template_id" class="mt-1" /></div>
                <div class="grid gap-3 sm:grid-cols-2"><div><label class="block text-sm font-medium">Primary color override</label><input v-model="form.settings.primary_color" placeholder="Use template default" class="mt-1 w-full rounded border-gray-300"><InputError :message="form.errors['settings.primary_color']" class="mt-1" /></div><div><label class="block text-sm font-medium">Secondary color override</label><input v-model="form.settings.secondary_color" placeholder="Use template default" class="mt-1 w-full rounded border-gray-300"><InputError :message="form.errors['settings.secondary_color']" class="mt-1" /></div></div>
                <div class="grid gap-3 sm:grid-cols-2"><div><label class="block text-sm font-medium">Heading font override</label><select v-model="form.settings.heading_font" class="mt-1 w-full rounded border-gray-300"><option value="">Use template default</option><option v-for="font in headingFonts" :key="font" :value="font">{{ font.replaceAll('_', ' ') }}</option></select></div><div><label class="block text-sm font-medium">Body font override</label><select v-model="form.settings.body_font" class="mt-1 w-full rounded border-gray-300"><option value="">Use template default</option><option v-for="font in bodyFonts" :key="font" :value="font">{{ font }}</option></select></div><div><label class="block text-sm font-medium">Text alignment override</label><select v-model="form.settings.text_alignment" class="mt-1 w-full rounded border-gray-300"><option value="">Use template default</option><option v-for="alignment in alignments" :key="alignment" :value="alignment">{{ alignment }}</option></select></div><div><label class="block text-sm font-medium">Layout variant override</label><select v-model="form.settings.layout_variant" class="mt-1 w-full rounded border-gray-300"><option value="">Use template default</option><option v-for="variant in layoutVariants" :key="variant" :value="variant">{{ variant }}</option></select></div></div>
                <fieldset><legend class="text-sm font-medium">Section visibility overrides</legend><div class="mt-2 grid gap-2 sm:grid-cols-2"><label v-for="key in sectionKeys" :key="key" class="text-sm"><span>{{ sectionLabels[key] }}</span><select v-model="form.settings.sections[key]" class="mt-1 w-full rounded border-gray-300"><option value="">Use template default</option><option value="show">Show</option><option value="hide">Hide</option></select></label></div></fieldset>
                <button :disabled="form.processing" class="rounded bg-indigo-600 px-4 py-2 text-white">Save invitation settings</button>
            </form>
            <section v-else class="rounded bg-white p-6 shadow"><h3 class="font-semibold">Invitation configuration</h3><p class="mt-2 text-gray-600">Support users can view this Event invitation but cannot change its template or presentation settings.</p><p class="mt-4">Selected template: <strong>{{ event.template?.name || 'Not selected' }}</strong></p></section>
            <section class="space-y-4"><div class="rounded bg-white p-5 shadow"><div class="flex flex-wrap items-end justify-between gap-3"><div><h3 class="font-semibold">Preview</h3><p class="mt-1 text-sm text-gray-600">Preview uses real safe Event data. Select a party for a personalized preview.</p></div><div><label class="block text-sm">Preview as invitation party</label><select v-model="previewPartyId" class="mt-1 rounded border-gray-300 text-sm"><option value="">No party selected</option><option v-for="party in parties" :key="party.id" :value="party.id">{{ party.name }}</option></select></div></div><Link :href="route('events.invitation.preview', { event: event.id, party_id: previewPartyId || undefined })" class="mt-4 inline-block rounded border border-indigo-600 px-3 py-2 text-sm text-indigo-600">Open full preview</Link></div><InvitationPreviewRenderer :invitation="previewInvitation" /></section>
        </div>
    </AuthenticatedLayout>
</template>
