<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InvitationPreviewRenderer from '@/Components/InvitationPreviewRenderer.vue';
import PageHeader from '@/Components/UI/PageHeader.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref, watch } from 'vue';
const props = defineProps<{ event:any; step:number; templates:any[]; overrides:any; resolvedSettings:any; activities:any[]; meals:any[]; previewInvitation:any; workflow:any; steps:any; timezones:string[] }>();
const optionalDetails=ref(false), dateValue=(v:any)=>v?v.slice(0,10):'', timeValue=(v:any)=>v?v.slice(0,5):'';
const details=useForm({event_type:props.event.event_type||'',title:props.event.title||'',host_name:props.event.host_name||'',second_host_name:props.event.second_host_name||'',description:props.event.description||''});
const location=useForm({main_date:dateValue(props.event.main_date),start_time:timeValue(props.event.start_time),end_time:timeValue(props.event.end_time),event_timezone:props.event.event_timezone||'',venue:props.event.venue||'',address:props.event.address||'',location_url:props.event.location_url||'',dress_code:props.event.dress_code||'',parking_information:props.event.parking_information||'',transportation_information:props.event.transportation_information||'',accommodation_information:props.event.accommodation_information||'',guest_information:props.event.guest_information||''});
const rsvp=useForm({rsvp_deadline:dateValue(props.event.rsvp_deadline)}), design=useForm({template_id:props.event.template_id||'',settings:{palette_key:props.overrides.palette_key||'',font_pair_key:props.overrides.font_pair_key||''}}), complete=useForm({});
const selectedTemplate=computed(()=>props.templates.find((t:any)=>t.id===Number(design.template_id))||null), paletteOptions=computed(()=>selectedTemplate.value?.palettes||[]), fontPairOptions=computed(()=>selectedTemplate.value?.font_pairs||[]);
const previewInvitation=computed(()=>({...props.previewInvitation,template:selectedTemplate.value?{name:selectedTemplate.value.name,component_key:selectedTemplate.value.component_key}:props.previewInvitation.template,settings:{...props.resolvedSettings,...(paletteOptions.value.find((x:any)=>x.key===design.settings.palette_key)||{}),...(fontPairOptions.value.find((x:any)=>x.key===design.settings.font_pair_key)||{})}}));
const dirty=computed(()=>details.isDirty||location.isDirty||rsvp.isDirty||design.isDirty), nextDay=computed(()=>!!location.start_time&&!!location.end_time&&location.end_time<location.start_time), state=(key:string)=>key==='schedule'?(props.steps.schedule?'Complete':'Optional'):(props.steps[key]?'Complete':'Incomplete');
const go=(step:number)=>{if(!dirty.value||window.confirm('You have unsaved changes. Leave this step without saving them?'))router.get(route('events.setup',{event:props.event.id,step}));};
const saveDetails=()=>details.patch(route('events.setup.save',{event:props.event.id,step:'details'})), saveLocation=()=>location.patch(route('events.setup.save',{event:props.event.id,step:'location'})), saveRsvp=()=>rsvp.patch(route('events.setup.save',{event:props.event.id,step:'rsvp'})), saveDesign=()=>design.transform((d:any)=>({template_id:d.template_id,settings:{palette_key:d.settings.palette_key||null,font_pair_key:d.settings.font_pair_key||null}})).patch(route('events.setup.save',{event:props.event.id,step:'design'})), activate=()=>complete.post(route('events.publication.publish',props.event.id),{onSuccess:()=>router.visit(route('events.show',props.event.id))});
watch(()=>design.template_id,(current,previous)=>{if(previous!==undefined&&current!==previous){design.settings.palette_key='';design.settings.font_pair_key='';}});
</script>
<template><Head title="Invitation Setup"/><AuthenticatedLayout><template #header><PageHeader title="Invitation Setup" subtitle="Build and preview your invitation."><template #actions><Link :href="route('events.show',event.id)" class="fe-btn fe-btn-secondary">Exit Setup</Link></template></PageHeader></template><div class="fe-page fe-page-standard space-y-6">
<nav class="grid gap-2 sm:grid-cols-5"><button v-for="(item,index) in [{key:'details',name:'Event Details'},{key:'location',name:'Date & Location'},{key:'schedule',name:'Schedule & RSVP'},{key:'design',name:'Choose Design'},{key:'review',name:'Review'}]" :key="item.key" class="rounded border px-3 py-3 text-left text-sm" :class="step===index+1?'border-indigo-600 bg-indigo-50 text-indigo-800':'border-gray-200 bg-white'" @click="go(index+1)"><span class="mr-1">{{step===index+1?'●':item.key==='review'?'5':state(item.key)==='Complete'?'✓':state(item.key)==='Optional'?'○':'!'}}</span>{{item.name}}<span v-if="item.key!=='review'" class="mt-1 block text-xs text-gray-500">{{state(item.key)}}</span></button></nav><p v-if="!workflow.can_manage" class="rounded border border-amber-200 bg-amber-50 p-4 text-sm">You can view this setup, but your role is read-only.</p>
<form v-if="step===1" class="space-y-4 rounded bg-white p-6 shadow" @submit.prevent="saveDetails"><fieldset :disabled="!workflow.can_manage"><div><h3 class="text-lg font-semibold">Event Details</h3><p class="text-sm text-gray-600">Tell guests what they are celebrating and who is hosting.</p></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><label>Event type<select v-model="details.event_type" class="mt-1 w-full rounded border-gray-300"><option value="">Select type</option><option v-for="type in ['wedding','engagement','bridal_shower','birthday','graduation','baptism','communion']" :key="type" :value="type">{{type.replaceAll('_',' ')}}</option></select><InputError :message="details.errors.event_type"/></label><label>Event title<input v-model="details.title" class="mt-1 w-full rounded border-gray-300"/><InputError :message="details.errors.title"/></label><label>Host name<input v-model="details.host_name" class="mt-1 w-full rounded border-gray-300"/><InputError :message="details.errors.host_name"/></label><label>Second host <span class="text-gray-500">(optional)</span><input v-model="details.second_host_name" class="mt-1 w-full rounded border-gray-300"/></label><label class="sm:col-span-2">Description <span class="text-gray-500">(optional)</span><textarea v-model="details.description" rows="4" class="mt-1 w-full rounded border-gray-300"/></label></div><button class="mt-4 rounded bg-indigo-600 px-4 py-2 text-white">Save & Continue</button></fieldset></form>
<form v-else-if="step===2" class="space-y-5 rounded bg-white p-6 shadow" @submit.prevent="saveLocation"><fieldset :disabled="!workflow.can_manage" class="space-y-5"><div><h3 class="text-lg font-semibold">Date & Location</h3><p class="text-sm text-gray-600">Times use the selected Event timezone.</p></div><h4 class="font-medium">Date & Time</h4><div class="grid gap-4 sm:grid-cols-2"><label>Event date<input v-model="location.main_date" type="date" class="mt-1 w-full rounded border-gray-300"/><InputError :message="location.errors.main_date"/></label><label>Event timezone<select v-model="location.event_timezone" class="mt-1 w-full rounded border-gray-300"><option v-for="zone in timezones" :key="zone" :value="zone">{{zone}}</option></select><InputError :message="location.errors.event_timezone"/></label><label>Start time<input v-model="location.start_time" type="time" class="mt-1 w-full rounded border-gray-300"/><InputError :message="location.errors.start_time"/></label><label>End time <span class="text-gray-500">(optional)</span><input v-model="location.end_time" type="time" class="mt-1 w-full rounded border-gray-300"/><p v-if="nextDay" class="mt-1 text-xs font-medium text-indigo-600">Next day</p><InputError :message="location.errors.end_time"/></label></div><h4 class="font-medium">Location</h4><div class="grid gap-4 sm:grid-cols-2"><label>Venue <span class="text-gray-500">(optional)</span><input v-model="location.venue" class="mt-1 w-full rounded border-gray-300"/></label><label>Address <span class="text-gray-500">(optional)</span><input v-model="location.address" class="mt-1 w-full rounded border-gray-300"/></label><label class="sm:col-span-2">Location URL <span class="text-gray-500">(optional)</span><input v-model="location.location_url" type="url" class="mt-1 w-full rounded border-gray-300"/></label></div><button type="button" class="text-sm text-indigo-600" @click="optionalDetails=!optionalDetails">{{optionalDetails?'Hide':'Show'}} Additional Guest Details (optional)</button><div v-if="optionalDetails" class="grid gap-4 rounded border p-4 sm:grid-cols-2"><label>Dress code<textarea v-model="location.dress_code" class="mt-1 w-full rounded border-gray-300"/></label><label>Parking information<textarea v-model="location.parking_information" class="mt-1 w-full rounded border-gray-300"/></label><label>Transportation information<textarea v-model="location.transportation_information" class="mt-1 w-full rounded border-gray-300"/></label><label>Accommodation information<textarea v-model="location.accommodation_information" class="mt-1 w-full rounded border-gray-300"/></label><label class="sm:col-span-2">Guest information<textarea v-model="location.guest_information" class="mt-1 w-full rounded border-gray-300"/></label></div><button class="rounded bg-indigo-600 px-4 py-2 text-white">Save & Continue</button></fieldset></form>
<form v-else-if="step===3" class="space-y-5 rounded bg-white p-6 shadow" @submit.prevent="saveRsvp"><fieldset :disabled="!workflow.can_manage" class="space-y-5"><div><h3 class="text-lg font-semibold">Schedule & RSVP</h3><p class="text-sm text-gray-600">Activities and meal choices are optional.</p></div><label>RSVP deadline <span class="text-gray-500">(optional)</span><input v-model="rsvp.rsvp_deadline" type="date" class="mt-1 block rounded border-gray-300"/><InputError :message="rsvp.errors.rsvp_deadline"/></label><div class="grid gap-4 sm:grid-cols-2"><section class="rounded border p-4"><h4 class="font-medium">Schedule</h4><p class="mt-1 text-sm text-gray-600">{{activities.length}} activities configured.</p><Link :href="route('events.activities.index',{event:event.id,from_setup:1})" class="mt-3 inline-block text-sm text-indigo-600">Manage schedule</Link></section><section class="rounded border p-4"><h4 class="font-medium">Meal options</h4><p class="mt-1 text-sm text-gray-600">{{meals.length}} meal options configured.</p><Link :href="route('events.meals.index',{event:event.id,from_setup:1})" class="mt-3 inline-block text-sm text-indigo-600">Manage meals</Link></section></div><button class="rounded bg-indigo-600 px-4 py-2 text-white">Save & Continue</button></fieldset></form>
<form v-else-if="step===4" class="space-y-5" @submit.prevent="saveDesign"><fieldset :disabled="!workflow.can_manage"><section class="rounded bg-white p-6 shadow"><h3 class="text-lg font-semibold">Choose Design</h3><p class="text-sm text-gray-600">Choose the invitation design that fits your event.</p><div class="mt-4 grid gap-4 md:grid-cols-3"><button v-for="template in templates" :key="template.id" type="button" class="rounded border p-4 text-left" :class="Number(design.template_id)===template.id?'border-indigo-600 ring-2 ring-indigo-100':'border-gray-200'" @click="design.template_id=template.id"><span class="block h-16 rounded" :class="template.component_key==='romantic-floral'?'bg-rose-100':template.component_key==='editorial-luxury'?'bg-amber-100':'bg-slate-800'"/><strong class="mt-3 block">{{template.name}}</strong><span class="mt-1 block text-sm text-gray-600">{{template.description}}</span></button></div><InputError :message="design.errors.template_id"/><div v-if="selectedTemplate" class="mt-5 grid gap-4 sm:grid-cols-2"><label>Color style<select v-model="design.settings.palette_key" class="mt-1 w-full rounded border-gray-300"><option value="">Use design default</option><option v-for="item in paletteOptions" :key="item.key" :value="item.key">{{item.label}}</option></select></label><label>Typography<select v-model="design.settings.font_pair_key" class="mt-1 w-full rounded border-gray-300"><option value="">Use design default</option><option v-for="item in fontPairOptions" :key="item.key" :value="item.key">{{item.label}}</option></select></label></div><button class="mt-5 rounded bg-indigo-600 px-4 py-2 text-white">Save & Continue</button></section></fieldset><InvitationPreviewRenderer :invitation="previewInvitation"/></form>
<section v-else class="space-y-5 rounded bg-white p-6 shadow"><div><h3 class="text-lg font-semibold">Review</h3><p class="text-sm text-gray-600">Check the required details before completing your invitation.</p></div><div class="space-y-3"><div v-for="(label,key) in {details:'Event Details',location:'Date & Location',schedule:'Schedule & RSVP',design:'Design'}" :key="key" class="flex items-center justify-between rounded border p-3"><span>{{label}} <span class="ml-2 text-sm text-gray-500">{{state(key)}}</span></span><button v-if="key!=='schedule'&&!steps[key]" class="text-sm text-indigo-600" @click="go(key==='details'?1:key==='location'?2:4)">Complete this step</button></div></div><p v-if="workflow.archived" class="text-red-700">This Event is archived and cannot be changed.</p><p v-else-if="workflow.live_version" class="text-emerald-700">Invitation is active. Saved changes go live immediately.</p><div class="flex justify-between"><Link :href="route('events.invitation.preview',event.id)" class="rounded border px-4 py-2">Preview Invitation</Link><button v-if="workflow.can_manage&&!workflow.live_version&&!workflow.archived" class="rounded bg-slate-900 px-4 py-2 text-white" @click="activate">Complete Invitation</button></div><div v-if="complete.errors" class="text-sm text-red-700"><p v-for="message in complete.errors" :key="message">{{message}}</p></div></section>
</div></AuthenticatedLayout></template>
