<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';

const props = defineProps<{ event: any; activities: any[]; guestInfo: Record<string, string | null>; customer: any; paymentSummary: any; canEdit: boolean; canViewGuests: boolean; canManageGuests: boolean; canViewRsvps: boolean; canManageRsvps: boolean; isAdmin: boolean }>();
const value = (item: string | null | undefined) => item || 'Not provided';
const date = (item: string | null | undefined) => item ? new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(`${item.slice(0, 10)}T00:00:00`)) : 'Not provided';
const money = (item: string | number | null | undefined) => item === null || item === undefined ? 'Not provided' : `$${Number(item).toFixed(2)}`;
const label = (item: string) => item.replaceAll('_', ' ');
</script>

<template>
    <Head :title="event.title" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center justify-between gap-4">
                <div><h2 class="text-xl font-semibold">{{ event.title }}</h2><p class="text-sm text-gray-600">{{ label(event.status) }}</p></div>
                <div class="flex flex-wrap gap-2"><Link :href="route('events.index')" class="rounded border border-gray-300 px-3 py-2 text-sm">Back to Events</Link><Link :href="route('events.invitation.edit', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">Invitation</Link><Link :href="route('events.activities.index', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">Schedule</Link><Link v-if="canViewGuests" :href="route('events.guests.index', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">Guests</Link><Link v-if="canViewRsvps" :href="route('events.rsvps.index', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">RSVPs</Link><Link v-if="canEdit" :href="route('events.edit', event.id)" class="rounded bg-indigo-600 px-3 py-2 text-sm text-white">Edit Event</Link></div>
            </div>
        </template>

        <div class="mx-auto max-w-5xl space-y-6 p-6">
            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Basic Information</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Event title</dt><dd>{{ event.title }}</dd></div><div><dt class="text-sm text-gray-500">Event type</dt><dd class="capitalize">{{ label(event.event_type) }}</dd></div><div><dt class="text-sm text-gray-500">Host name</dt><dd>{{ value(event.host_name) }}</dd></div><div><dt class="text-sm text-gray-500">Second host / partner</dt><dd>{{ value(event.second_host_name) }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-gray-500">Description</dt><dd class="whitespace-pre-line">{{ value(event.description) }}</dd></div><div><dt class="text-sm text-gray-500">Current status</dt><dd class="capitalize">{{ label(event.status) }}</dd></div></dl></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Date &amp; Time</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Main date</dt><dd>{{ date(event.main_date) }}</dd></div><div><dt class="text-sm text-gray-500">RSVP deadline</dt><dd>{{ date(event.rsvp_deadline) }}</dd></div><div><dt class="text-sm text-gray-500">Start time</dt><dd>{{ value(event.start_time) }}</dd></div><div><dt class="text-sm text-gray-500">End time</dt><dd>{{ value(event.end_time) }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-gray-500">Event timezone</dt><dd>{{ value(event.event_timezone) }}</dd></div></dl></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><div class="mb-4 flex items-center justify-between gap-3"><h3 class="text-lg font-semibold">Schedule</h3><Link :href="route('events.activities.index', event.id)" class="text-sm text-indigo-600 underline">View schedule</Link></div><div v-if="activities.length" class="space-y-3"><article v-for="activity in activities" :key="activity.id" class="rounded border p-4"><div class="flex flex-wrap items-start justify-between gap-2"><div><h4 class="font-medium">{{ activity.title }}</h4><p v-if="activity.activity_type" class="text-sm capitalize text-gray-600">{{ label(activity.activity_type) }}</p></div><span class="rounded bg-gray-100 px-2 py-1 text-xs">{{ activity.is_active ? 'Active' : 'Inactive' }}</span></div><p class="mt-2 text-sm text-gray-700">{{ activity.date }} · {{ activity.start_time }}<span v-if="activity.end_time"> – <span v-if="activity.end_date !== activity.date">{{ activity.end_date }}, </span>{{ activity.end_time }}</span></p><p v-if="activity.venue || activity.address" class="mt-1 text-sm text-gray-600">{{ activity.venue || 'Location to be confirmed' }}<span v-if="activity.address"> · {{ activity.address }}</span></p><a v-if="activity.location_url" :href="activity.location_url" target="_blank" rel="noopener noreferrer" class="mt-2 inline-block text-sm text-indigo-600 underline">Open location</a></article></div><p v-else class="text-gray-600">No schedule activities have been added.</p></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Location</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Venue</dt><dd>{{ value(event.venue) }}</dd></div><div><dt class="text-sm text-gray-500">Address</dt><dd>{{ value(event.address) }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-gray-500">Location URL</dt><dd><a v-if="event.location_url" :href="event.location_url" target="_blank" rel="noopener noreferrer" class="text-indigo-600 underline">Open Location</a><span v-else>Not provided</span></dd></div></dl></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Guest Information</h3><dl v-if="Object.values(guestInfo).some(Boolean)" class="grid gap-4 sm:grid-cols-2"><div v-if="guestInfo.dress_code"><dt class="text-sm text-gray-500">Dress code</dt><dd class="whitespace-pre-line">{{ guestInfo.dress_code }}</dd></div><div v-if="guestInfo.parking_information"><dt class="text-sm text-gray-500">Parking</dt><dd class="whitespace-pre-line">{{ guestInfo.parking_information }}</dd></div><div v-if="guestInfo.transportation_information"><dt class="text-sm text-gray-500">Transportation</dt><dd class="whitespace-pre-line">{{ guestInfo.transportation_information }}</dd></div><div v-if="guestInfo.accommodation_information"><dt class="text-sm text-gray-500">Accommodation</dt><dd class="whitespace-pre-line">{{ guestInfo.accommodation_information }}</dd></div><div v-if="guestInfo.guest_information" class="sm:col-span-2"><dt class="text-sm text-gray-500">Additional guest information</dt><dd class="whitespace-pre-line">{{ guestInfo.guest_information }}</dd></div></dl><p v-else class="text-gray-600">No guest information provided.</p></section>

            <section v-if="isAdmin && customer" class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Customer</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Customer name</dt><dd>{{ customer.name }}</dd></div><div><dt class="text-sm text-gray-500">Contact name</dt><dd>{{ value(customer.contact_name) }}</dd></div><div><dt class="text-sm text-gray-500">Email</dt><dd>{{ value(customer.email) }}</dd></div><div><dt class="text-sm text-gray-500">Phone</dt><dd>{{ value(customer.phone) }}</dd></div></dl></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Package</h3><dl v-if="event.package" class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Package name</dt><dd>{{ event.package.name }}</dd></div><div><dt class="text-sm text-gray-500">State</dt><dd>{{ event.package.is_active ? 'Active' : 'Inactive' }}</dd></div><div><dt class="text-sm text-gray-500">Guest capacity</dt><dd>{{ event.package.minimum_guests }}–{{ event.package.maximum_guests }} guests</dd></div><div><dt class="text-sm text-gray-500">Price</dt><dd>{{ money(event.package.price) }}</dd></div></dl><p v-else class="text-gray-600">Not provided</p></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Payment Summary</h3><dl v-if="paymentSummary" class="grid gap-4 sm:grid-cols-3"><div><dt class="text-sm text-gray-500">Package price</dt><dd>{{ money(paymentSummary.package_price) }}</dd></div><div><dt class="text-sm text-gray-500">Original amount</dt><dd>{{ money(paymentSummary.original_amount) }}</dd></div><div><dt class="text-sm text-gray-500">Discount</dt><dd>{{ money(paymentSummary.discount) }}</dd></div><div><dt class="text-sm text-gray-500">Coupon</dt><dd>{{ paymentSummary.coupon_code || 'No coupon' }}</dd></div><div><dt class="text-sm text-gray-500">Final amount</dt><dd>{{ money(paymentSummary.final_amount) }}</dd></div><div><dt class="text-sm text-gray-500">Total paid</dt><dd>{{ money(paymentSummary.paid_amount) }}</dd></div><div><dt class="text-sm text-gray-500">Remaining balance</dt><dd>{{ money(paymentSummary.remaining_amount) }}</dd></div><div><dt class="text-sm text-gray-500">Payment status</dt><dd class="capitalize">{{ label(paymentSummary.status) }}</dd></div></dl><p v-else class="text-gray-600">No payment recorded yet.</p><div v-if="paymentSummary?.transactions?.length" class="mt-5"><h4 class="mb-2 font-medium">Payment history</h4><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 text-gray-600"><tr><th class="p-2">Amount</th><th class="p-2">Date</th><th class="p-2">Method</th><th class="p-2">Reference</th></tr></thead><tbody><tr v-for="transaction in paymentSummary.transactions" :key="transaction.id" class="border-t"><td class="p-2">{{ money(transaction.amount) }}</td><td class="p-2">{{ transaction.payment_date || 'Not provided' }}</td><td class="p-2">{{ value(transaction.payment_method) }}</td><td class="p-2">{{ value(transaction.reference) }}</td></tr></tbody></table></div></div></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">Event Members</h3><div v-if="event.members.length" class="divide-y"><div v-for="member in event.members" :key="member.id" class="flex justify-between py-3"><span>{{ member.name }}</span><span class="capitalize text-gray-600">{{ member.pivot.role }}</span></div></div><p v-else class="text-gray-600">No members are assigned.</p></section>

            <section class="rounded bg-white p-6 shadow sm:rounded-lg"><h3 class="mb-4 text-lg font-semibold">System Information</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-gray-500">Created date</dt><dd>{{ date(event.created_at) }}</dd></div><div><dt class="text-sm text-gray-500">Last updated</dt><dd>{{ date(event.updated_at) }}</dd></div></dl></section>
        </div>
    </AuthenticatedLayout>
</template>
