<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import ConfirmationModal from '@/Components/ConfirmationModal.vue';
import InputError from '@/Components/InputError.vue';
import ValidationSummary from '@/Components/ValidationSummary.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { reactive, ref } from 'vue';

const props = defineProps<{ event: any; parties: any[]; summary: any; filters: any; canManage: boolean }>();
const filters = reactive({ ...props.filters });
const form = useForm({ name: '', primary_contact_name: '', email: '', phone: '', maximum_party_size: 1, table_name: '', notes: '' });
const pendingParty = ref<any>(null);
const apply = () => router.get(route('events.guests.index', props.event.id), filters, { preserveState: true, replace: true });
const reset = () => { filters.search = ''; filters.active = ''; filters.members = ''; apply(); };
const updateActive = () => router.patch(route('events.guests.active', [props.event.id, pendingParty.value.id]), { is_active: !pendingParty.value.is_active }, { onFinish: () => pendingParty.value = null });
</script>

<template>
    <Head :title="`${event.title} guests`" />
    <AuthenticatedLayout>
        <template #header><div class="flex items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">Guest management</h2><p class="text-sm text-gray-600">{{ event.title }}</p></div><Link :href="route('events.show', event.id)" class="rounded border border-gray-300 px-3 py-2 text-sm">Back to Event</Link></div></template>
        <div class="mx-auto max-w-7xl space-y-5 p-6">
            <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div class="rounded bg-white p-4 shadow"><p class="text-sm text-gray-500">Package capacity</p><p class="text-xl font-semibold">{{ summary.package_capacity ?? 'Not assigned' }}</p></div><div class="rounded bg-white p-4 shadow"><p class="text-sm text-gray-500">Allocated capacity</p><p class="text-xl font-semibold">{{ summary.allocated_capacity }}</p></div><div class="rounded bg-white p-4 shadow"><p class="text-sm text-gray-500">Remaining capacity</p><p class="text-xl font-semibold">{{ summary.remaining_capacity ?? 'Not available' }}</p></div><div class="rounded bg-white p-4 shadow"><p class="text-sm text-gray-500">Invitation parties</p><p class="text-xl font-semibold">{{ summary.party_count }}</p></div><div class="rounded bg-white p-4 shadow"><p class="text-sm text-gray-500">Listed members</p><p class="text-xl font-semibold">{{ summary.member_count }}</p></div></section>

            <section v-if="canManage" class="bg-white p-4 shadow"><h3 class="mb-3 font-semibold">Add invitation party</h3><form @submit.prevent="form.post(route('events.guests.store', event.id), { onSuccess: () => form.reset() })" class="grid gap-3 sm:grid-cols-3"><div><label class="mb-1 block text-sm">Party / invitation name</label><input v-model="form.name" required class="w-full rounded border-gray-300" /><InputError :message="form.errors.name" class="mt-1" /></div><div><label class="mb-1 block text-sm">Primary contact name</label><input v-model="form.primary_contact_name" class="w-full rounded border-gray-300" /><InputError :message="form.errors.primary_contact_name" class="mt-1" /></div><div><label class="mb-1 block text-sm">Maximum party size</label><input v-model="form.maximum_party_size" type="number" min="1" required class="w-full rounded border-gray-300" /><InputError :message="form.errors.maximum_party_size" class="mt-1" /></div><div><label class="mb-1 block text-sm">Email</label><input v-model="form.email" type="email" class="w-full rounded border-gray-300" /><InputError :message="form.errors.email" class="mt-1" /></div><div><label class="mb-1 block text-sm">Phone</label><input v-model="form.phone" class="w-full rounded border-gray-300" /><InputError :message="form.errors.phone" class="mt-1" /></div><div><label class="mb-1 block text-sm">Table</label><input v-model="form.table_name" class="w-full rounded border-gray-300" /><InputError :message="form.errors.table_name" class="mt-1" /></div><div class="sm:col-span-3"><label class="mb-1 block text-sm">Internal notes</label><textarea v-model="form.notes" class="w-full rounded border-gray-300" /></div><div class="sm:col-span-3"><ValidationSummary :errors="form.errors" /></div><button class="w-fit rounded bg-indigo-600 px-3 py-2 text-white">Add invitation party</button></form></section>

            <form @submit.prevent="apply" class="flex flex-wrap gap-2"><input v-model="filters.search" placeholder="Search party, contact, email, phone, member" class="rounded border-gray-300" /><select v-model="filters.active" class="rounded border-gray-300"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select v-model="filters.members" class="rounded border-gray-300"><option value="">All parties</option><option value="with">Has members</option><option value="without">No members</option></select><button class="rounded bg-gray-800 px-3 text-white">Search</button><button type="button" @click="reset" class="text-gray-600">Reset</button></form>

            <div class="overflow-x-auto bg-white shadow"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 text-gray-600"><tr><th class="p-3">Party</th><th class="p-3">Primary contact</th><th class="p-3">Email / phone</th><th class="p-3">Maximum size</th><th class="p-3">Listed members</th><th class="p-3">Table</th><th class="p-3">Status</th><th class="p-3">Actions</th></tr></thead><tbody><tr v-for="party in parties" :key="party.id" class="border-t"><td class="p-3 font-medium">{{ party.name }}</td><td class="p-3">{{ party.primary_contact_name || 'Not provided' }}</td><td class="p-3">{{ party.email || 'No email' }}<br /><span class="text-gray-500">{{ party.phone || 'No phone' }}</span></td><td class="p-3">{{ party.maximum_party_size }}</td><td class="p-3">{{ party.members_count }}</td><td class="p-3">{{ party.table_name || 'Not assigned' }}</td><td class="p-3">{{ party.is_active ? 'Active' : 'Inactive' }}</td><td class="p-3"><div class="flex items-center gap-2 whitespace-nowrap"><Link :href="route('events.guests.show', [event.id, party.id])" class="text-indigo-600">View</Link><span v-if="canManage" class="text-gray-300">|</span><Link v-if="canManage" :href="`${route('events.guests.show', [event.id, party.id])}#party-edit`" class="text-indigo-600">Edit</Link><span v-if="canManage" class="text-gray-300">|</span><button v-if="canManage" @click="pendingParty = party" class="text-indigo-600">{{ party.is_active ? 'Deactivate' : 'Reactivate' }}</button></div></td></tr></tbody></table><p v-if="!parties.length" class="p-5 text-gray-600">No invitation parties match your search or filters.</p></div>
        </div>
        <ConfirmationModal :show="!!pendingParty" :title="pendingParty?.is_active ? 'Deactivate invitation party?' : 'Activate invitation party?'" :message="pendingParty?.is_active ? 'This party will no longer reserve event capacity.' : 'This party will reserve its maximum party size from event capacity again.'" :confirm-label="pendingParty?.is_active ? 'Deactivate party' : 'Activate party'" @close="pendingParty = null" @confirm="updateActive" />
    </AuthenticatedLayout>
</template>
