<?php

// Local visual QA only. Paths are relative to storage/app/qa/reference-template-assets.
// These files must never be persisted to Event content or published invitations.
return [
    // Reference media requested by the owner for local demos only; no production license implied.
    '5' => [
        'envelopeBottom' => 'template-5/envelopeBottom.png',
        'envelopeLeft' => 'template-5/envelopeLeft.png',
        'envelopeRight' => 'template-5/envelopeRight.png',
        'envelopeTop' => 'template-5/envelopeTop.png',
        'envelopeSeal' => 'template-5/envelopeSeal.png',
        'envelope' => 'template-5/envelope.png',
        'envelopeVideo' => 'template-5/envelope-opening.mp4',
        'heroPoster' => 'template-5/italian-villa-terrace.jpg',
        'heroVideo' => 'template-5/italian-villa-terrace.mp4',
        'scratchTexture' => 'template-5/scratch-coating.svg',
        'letterBack' => 'template-5/letter-back.png',
        'letterFront' => 'template-5/letter-front.png',
        'letterFlower' => 'template-5/letter-flower.png',
        'scheduleLeft' => 'template-5/schedule-left.png',
        'scheduleRight' => 'template-5/schedule-right.png',
        'venuePhoto' => 'template-5/venue.jpg',
        'locationIcon' => 'template-5/location-icon.png',
        'dressDivider' => 'template-5/dress-divider.png',
        'outfit1' => 'template-5/outfit-1.jpg',
        'outfit2' => 'template-5/outfit-2.jpg',
        'outfit3' => 'template-5/outfit-3.jpg',
        'outfit4' => 'template-5/outfit-4.jpg',
        'outfit5' => 'template-5/outfit-5.jpg',
        'outfit6' => 'template-5/outfit-6.jpg',
        'outfit7' => 'template-5/outfit-7.jpg',
        'outfit8' => 'template-5/outfit-8.jpg',
        'outfit9' => 'template-5/outfit-9.jpg',
        'outfit10' => 'template-5/outfit-10.jpg',
        'endingPhoto' => 'template-5/ending-couple.jpg',
    ],
    '6' => [
        'envelopePaper' => 'template-6/envelopePaper.png',
        'envelopeFront' => 'template-6/envelopeFront.png',
        'envelope' => 'template-6/envelope.png',
        'envelopeVideo' => 'template-6/envelope-opening.mp4',
        'heroPoster' => 'template-6/moroccan-arch.jpg',
        'heroVideo' => 'template-6/moroccan-arch.mp4',
        'invitationFrame' => 'template-6/invitation-frame.png',
        'calligraphy' => 'template-6/calligraphy.png',
        'invitationOrnament' => 'template-6/invitation-ornament.png',
        'flowerLine' => 'template-6/flower-line.png',
        'divider' => 'template-6/divider.png',
        'timelineMarker' => 'template-6/timeline-marker.png',
        'timelineFlower' => 'template-6/timeline-flower.png',
        'locationIcon' => 'template-6/location-icon.png',
        'venueArt' => 'template-6/venue.png',
        'dressArt' => 'template-6/dress.png',
        'mapFrame' => 'template-6/map-frame.svg',
        'endingArt' => 'template-6/ending-art.png',
        'endingDivider' => 'template-6/ending-divider.png',
        'endingFlower' => 'template-6/ending-flower.png',
        'endingVideo' => 'template-6/ending.mp4',
        'endingPoster' => 'template-6/ending.jpg',
    ],
    '7' => [
        'envelope' => 'template-7/envelope.png',
        'envelopeVideo' => 'template-7/envelope-opening.mp4',
        'heroPoster' => 'template-7/swans.jpg',
        'heroVideo' => 'template-7/swans.mov',
        'heroLeft' => 'template-7/hero-left.png',
        'heroRight' => 'template-7/hero-right.png',
        'paper' => 'template-7/paper.png',
        'calligraphy' => 'template-7/calligraphy.png',
        'flourishLeft' => 'template-7/flourish-left.png',
        'flourishRight' => 'template-7/flourish-right.png',
        'scheduleTop' => 'template-7/schedule-top.png',
        'scheduleBottom' => 'template-7/schedule-bottom.png',
        'timelineRose' => 'template-7/timeline-rose.png',
        'venueDivider' => 'template-7/venue-divider.png',
        'venueArt' => 'template-7/venue.png',
        'butterfly1' => 'template-7/butterfly-1.png',
        'butterfly2' => 'template-7/butterfly-2.png',
        'butterfly3' => 'template-7/butterfly-3.png',
        'butterfly4' => 'template-7/butterfly-4.png',
        'butterfly5' => 'template-7/butterfly-5.png',
        'butterfly6' => 'template-7/butterfly-6.png',
        'mapFrame' => 'template-7/map-frame.svg',
        'mapTop' => 'template-7/map-top.png',
        'mapBottom' => 'template-7/map-bottom.png',
        'preferencePaper' => 'template-7/preference-paper.png',
        'preferenceRight' => 'template-7/preference-right.png',
        'preferenceLeft' => 'template-7/preference-left.png',
        'rsvpSeal' => 'template-7/rsvp-seal.png',
        'endingPhoto' => 'template-7/ending-couple.jpg',
        'endingPaper' => 'template-7/ending-paper.png',
    ],
    '4' => [
        'heroVideo' => 'template-4/video/hero-bg.mp4',
        'heroPoster' => 'template-4/images/hero-poster.jpg',
        'countdownArt' => 'template-4/artwork/countdown.png',
        'curtainLeft' => 'template-4/artwork/left.png',
        'curtainCenter' => 'template-4/artwork/center.png',
        'curtainRight' => 'template-4/artwork/right.png',
        'flowerCluster' => 'template-4/artwork/white-cluster.png',
        'flowerBouquet' => 'template-4/artwork/white-bouquet.png',
        'ceremonyArt' => 'template-4/artwork/venue.png',
        'celebrationArt' => 'template-4/artwork/venue-1.png',
        'dressArt' => 'template-4/artwork/dress-code.png',
        'storyPhoto' => 'template-4/images/1788244861-o3gUdcYg-55e492bdcc038c08fa290b9dd24276ee.jpg',
        'giftFlowers' => 'template-4/artwork/gifts.png',
    ],
    '1' => [
        'opening' => 'template-1/images/opening-couple.webp',
        'paperSea' => 'template-1/artwork/paper-sea.webp',
        'paperCoast' => 'template-1/artwork/paper-coast.webp',
        'paperCorner' => 'template-1/artwork/paper-coast-corner.webp',
        'paperBorder' => 'template-1/artwork/paper-coast-border.webp',
        'groomIcon' => 'template-1/artwork/groom.svg',
        'brideIcon' => 'template-1/artwork/bride.svg',
        'fallingLeaf' => 'template-1/artwork/realLeaf1.png',
    ],
    '2' => [
        'curtainStill' => 'template-2/images/curtain-closed-Bpkadld4.jpg',
        'curtainVideo' => 'template-2/video/curtain-video-BAKLj3Y5.mp4',
        'menuFrame' => 'template-2/artwork/menu-frame-BFE5kCs7.png',
        'scratchGold' => 'template-2/artwork/scratch-gold-DQrdz0lH.png',
        'giftIcon' => 'template-2/artwork/gift-icon-BssCdzah.png',
    ],
    '3' => [
        'swansPoster' => 'template-3/images/swans-poster.jpg',
        'swansVideo' => 'template-3/video/swans.mp4',
        'flourishLeft' => 'template-3/artwork/flourish-left.png',
        'flourishRight' => 'template-3/artwork/flourish-right.png',
        'roseBouquet' => 'template-3/artwork/rose-bouquet.png',
        'floral' => 'template-3/artwork/floral-a.png',
        'waxSeal' => 'template-3/artwork/wax-seal.png',
        'fallingPetal' => 'template-3/artwork/petal.png',
    ],
];
