<script setup lang="ts">
import { computed, ref } from 'vue';
import ReferenceAsset from './ReferenceAsset.vue';
import DemoEnvelope from './DemoEnvelope.vue';
import WebgencyRsvpDemo from './WebgencyRsvpDemo.vue';
import { useReferenceExperience } from './referenceExperience';
import './webgencyDemos.css';
import NativeEventSections from './NativeEventSections.vue';
import { familyGreeting, invitationText } from './invitationText';
import { webgencyEventContent } from './webgencyEventContent';
const props = defineProps<{ invitation: any }>();
const invitation = computed(() => webgencyEventContent(props.invitation, 'blossom'));
const realRsvpOpen = ref(false);
const t = (text: string) => invitationText(props.invitation, text);
const root = ref<HTMLElement | null>(null);
const { countdown } = useReferenceExperience(() => props.invitation, root);
const media = computed(() => props.invitation.media || {});
</script>
<template>
    <article ref="root" class="webgency-demo blossom-demo" :class="{ 'real-event': !invitation.reference_demo }" :lang="invitation.content?.primary_locale || 'fr'">
        <DemoEnvelope v-if="invitation.reference_demo || media.envelopeFront || media.envelope" mobile-only theme="blossom" :media="media" :image="media.envelope" :video="media.envelopeVideo" :label="invitation.reference_demo ? 'Appuyez pour ouvrir' : t('Tap to open')" name="Blossom & Oud floral envelope" />
        <header class="wg-section blossom-hero"><div class="wg-canvas">
            <video v-if="media.heroVideo" :src="media.heroVideo" :poster="media.heroPoster" autoplay loop muted playsinline aria-hidden="true" />
            <ReferenceAsset v-else class="wg-photo" name="Moroccan arch · chandelier, drapes and palm garden" :src="media.heroPoster" />
            <div class="blossom-names"><h1 class="wg-script"><span>{{ invitation.event.host_name }}</span><small>&amp;</small><span>{{ invitation.event.second_host_name }}</span></h1><p>{{ invitation.event.date_label }}</p><p>{{ invitation.event.start_time }}</p></div>
        </div></header>
        <section class="wg-section blossom-invitation"><div class="wg-canvas">
            <ReferenceAsset class="wg-art blossom-frame" name="frsame_1 · ornate invitation frame" :src="media.invitationFrame" />
            <ReferenceAsset class="wg-art blossom-calligraphy" name="Group_204_2 · Arabic calligraphy" :src="media.calligraphy" />
            <ReferenceAsset class="wg-art blossom-symbol" name="Vector · invitation ornament" :src="media.invitationOrnament" />
            <div class="blossom-arabic" :lang="invitation.reference_demo ? 'ar' : invitation.content?.primary_locale" :dir="invitation.reference_demo || invitation.content?.primary_locale === 'ar' ? 'rtl' : 'ltr'" data-reveal><p v-if="invitation.party_name" data-family-greeting>{{ familyGreeting(invitation) }}</p><p v-for="paragraph in invitation.content.introduction" :key="paragraph">{{ paragraph }}</p></div>
            <h2>{{ invitation.event.venue }}</h2><ReferenceAsset class="wg-art blossom-flower-line" name="line_flower_1 · floral line" :src="media.flowerLine" />
        </div></section>
        <section class="wg-section blossom-countdown"><h2 class="wg-heading">{{ invitation.reference_demo ? 'La Célébration Commence' : t('The Celebration Begins In') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /><div class="wg-countdown" dir="ltr"><template v-for="(value,i) in invitation.reference_demo?.display_countdown || countdown" :key="i"><span v-if="i" aria-hidden="true">:</span><div><strong>{{ value }}</strong><small>{{ t(['Days','Hours','Minutes','Seconds'][i]) }}</small></div></template></div></section>
        <section class="wg-section blossom-schedule"><h2 class="wg-heading">{{ invitation.reference_demo ? "Chronologie de l'événement" : t('Schedule of Events') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /><ol><li v-for="(activity,i) in invitation.event.activities" :key="i"><time>{{ activity.start_time }}</time><ReferenceAsset class="wg-art blossom-timeline-marker" name="Decoration_elements · timeline motif" :src="media.timelineMarker" /><p data-reveal>{{ activity.title }}</p><div v-if="!invitation.reference_demo" class="native-activity-details"><p>{{ activity.venue }}</p><p>{{ activity.address }}</p><p>{{ activity.description }}</p><a v-if="activity.location_url" :href="activity.location_url" target="_blank" rel="noopener noreferrer">{{ t('Directions') }}</a></div></li><ReferenceAsset class="wg-art blossom-timeline-flower" name="flower-decor · moving timeline flower" :src="media.timelineFlower" /></ol></section>
        <section class="wg-section blossom-venue"><h2 class="wg-heading">{{ invitation.reference_demo ? 'Lieu' : t('Location') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /><ReferenceAsset class="wg-art blossom-pin" name="ic_baseline-place · location pin" :src="media.locationIcon" /><h3>{{ invitation.event.venue }}</h3><p>{{ invitation.event.address }}</p><ReferenceAsset class="wg-art blossom-venue-art" name="Group_222 · Beldi Country Club illustration" :src="media.venueArt" /></section>
        <section v-if="invitation.reference_demo || invitation.event.dress_code" class="wg-section blossom-dress"><h2 class="wg-heading">{{ t('Dress Code') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /><ReferenceAsset class="wg-art blossom-dress-art" name="People in elegant attire illustration" :src="media.dressArt" /><p class="wg-body">{{ invitation.content.dress_intro }}</p><h3 v-if="invitation.reference_demo" class="wg-script">Color palette</h3><div v-if="invitation.reference_demo" class="blossom-palette"><span v-for="color in invitation.content.palette" :key="color" :style="{background:color}" :aria-label="`Color ${color}`"></span></div></section>
        <section v-if="invitation.reference_demo" class="wg-section blossom-attire" lang="en"><h3 class="wg-script">Ladies</h3><p class="wg-body">{{ invitation.content.ladies }}</p><h3 class="wg-script">Gentlemen</h3><p class="wg-body">{{ invitation.content.gentlemen }}</p></section>
        <NativeEventSections :invitation="invitation" /><section class="wg-section blossom-rsvp" data-section="rsvp"><h2 class="wg-heading">{{ invitation.reference_demo ? 'Confirmez Votre Présence' : t('Confirm Your Attendance') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /><WebgencyRsvpDemo v-if="invitation.reference_demo" theme="blossom" /><div v-else class="native-rsvp-panel"><slot /></div></section>
        <section v-if="invitation.event.map_url" class="wg-section blossom-map-heading"><h2 class="wg-heading">{{ invitation.reference_demo ? 'Itinéraire Google Maps' : t('Directions on Google Maps') }}</h2><ReferenceAsset class="wg-art blossom-divider" name="line-divider2 · gold divider" :src="media.divider" /></section>
        <div v-if="invitation.event.map_url" class="wg-map"><iframe :src="invitation.event.map_url" :title="`Map: ${invitation.event.venue}`" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><ReferenceAsset class="wg-art" name="Rectangle_242 · map border" :src="media.mapFrame" /></div>
        <footer v-if="invitation.content?.ending_enabled !== false" class="wg-section blossom-ending" data-section="ending"><ReferenceAsset class="wg-art blossom-ending-art" name="Floral champagne illustration" :src="media.endingArt" /><h2 class="wg-heading">{{ invitation.content?.ending_title || (invitation.reference_demo ? 'Au plaisir de vous accueillir' : t('Hope to see you there!')) }}</h2><p v-if="invitation.content?.ending_message">{{ invitation.content.ending_message }}</p><ReferenceAsset class="wg-art blossom-ending-divider" name="decor-line_1 · ending divider" :src="media.endingDivider" /><ReferenceAsset class="wg-art blossom-ending-flower" name="Fine-line flowers motif" :src="media.endingFlower" /></footer>
        <div v-if="invitation.content?.ending_enabled !== false" class="wg-section blossom-ending-film"><div class="wg-canvas"><video v-if="media.endingVideo" :src="media.endingVideo" autoplay muted playsinline loop aria-label="Closing floral animation"></video><ReferenceAsset v-else class="wg-photo" name="Closing animation · Untitled Project.mp4" :src="media.endingPoster" /></div></div>
    </article>
</template>
<style scoped>
.blossom-demo{--wg-paper:#f9e6d4;--wg-accent:#866739;--wg-ink:#2a2a2a}.blossom-hero,.blossom-hero>.wg-canvas{height:782px}.blossom-hero video,.blossom-hero .wg-photo{width:100%;height:782px}.blossom-names{position:absolute;top:320px;left:0;right:0;color:#866739}.blossom-names h1{font-size:59px;line-height:64px}.blossom-names h1>span{display:block}.blossom-names h1>small{display:block;font-size:28px;line-height:28px}.blossom-names p{font:19px/25px Georgia,serif}.blossom-names h1+p{margin-top:4px}
.blossom-invitation,.blossom-invitation>.wg-canvas{height:780px}.blossom-frame{width:356px;height:734px;left:calc(50% - 178px);top:43px}.blossom-calligraphy{width:209px;height:61px;left:calc(50% - 104px);top:159px}.blossom-symbol{width:37px;height:35px;left:calc(50% - 18px);top:234px}.blossom-arabic{position:absolute;top:285px;left:calc(50% - 122.5px);width:245px;font:22px/29px Georgia,serif;color:#454545}.blossom-arabic p{white-space:pre-line}.blossom-arabic p+p{margin-top:22px}.blossom-invitation h2{position:absolute;top:617px;left:0;right:0;font:34px/43px 'WG Script Fallback',Georgia,serif;color:#876836}.blossom-flower-line{width:217px;height:52px;left:calc(50% - 108px);top:662px}
.blossom-divider{width:139px;height:28px;left:calc(50% - 69.5px);top:110px}.blossom-countdown{height:248px;padding-top:45px}.blossom-countdown .wg-countdown{margin-top:50px;color:#866739}.blossom-countdown .wg-countdown strong{font-size:26px}.blossom-countdown .wg-countdown small{font-size:11px}.blossom-countdown .wg-countdown{gap:8px}
.blossom-schedule{height:489px;padding-top:45px}.blossom-schedule ol{list-style:none;position:relative;width:300px;max-width:calc(100% - 32px);padding:0;margin:64px auto 0}.blossom-schedule ol:before{content:'';position:absolute;left:calc(50% - 1px);top:27px;height:258px;width:2px;background:#ac9778}.blossom-schedule li{display:grid;grid-template-columns:1fr 1fr;column-gap:62px;align-items:center;height:82px;position:relative}.blossom-schedule time{font:30px/47px Georgia,serif}.blossom-schedule li p{font:20px/22px Georgia,serif}.blossom-timeline-marker{width:14px;height:16px;left:calc(50% - 7px);top:26px;z-index:1!important}.blossom-timeline-flower{width:55px;height:55px;left:calc(50% - 27px);top:6px;z-index:2!important}
.blossom-venue{height:541px;padding-top:45px}.blossom-pin{width:36px;height:36px;left:calc(50% - 18px);top:151px}.blossom-venue h3{position:absolute;top:203px;left:0;right:0;font:23px/36px Georgia,serif;color:#454545}.blossom-venue>p{position:absolute;top:235px;left:0;right:0;font:19px/29px Georgia,serif}.blossom-venue-art{width:420px;max-width:100%;height:252px;left:50%;transform:translateX(-50%);top:285px}
.blossom-dress{height:579px;padding-top:44px}.blossom-dress-art{width:236px;height:165px;left:calc(50% - 118px);top:154px}.blossom-dress>.wg-body{position:absolute;top:342px;width:335px;left:50%;transform:translateX(-50%);font:21px/25px Georgia,serif}.blossom-dress h3{position:absolute;top:446px;left:0;right:0;font-size:32px;line-height:50px;color:#866739}.blossom-palette{position:absolute;top:507px;left:0;right:0;display:flex;gap:12px;justify-content:center}.blossom-palette span{display:block;width:57px;height:57px;border:1px solid #fffaf8;border-radius:50%}
.blossom-attire{height:249px}.blossom-attire h3{font-size:33px;line-height:51px;color:#866739}.blossom-attire .wg-body{width:301px;font:21px/25px Georgia,serif;margin-top:3px}.blossom-attire .wg-body+h3{margin-top:27px}
.blossom-rsvp{height:529px;padding-top:45px}.blossom-rsvp :deep(.wg-rsvp){margin-top:58px}.blossom-map-heading{height:159px;padding-top:45px}.blossom-ending{height:371px;padding-top:196px}.blossom-ending-art{width:227px;height:171px;left:calc(50% - 125px);top:34px}.blossom-ending-divider{width:165px;height:25px;left:calc(50% - 82px);top:260px}.blossom-ending-flower{width:50px;height:53px;left:calc(50% - 25px);top:290px}.blossom-ending-film,.blossom-ending-film .wg-canvas,.blossom-ending-film video,.blossom-ending-film .wg-photo{height:791px}.blossom-ending-film video,.blossom-ending-film .wg-photo{width:100%}
@media(max-width:600px){.blossom-frame{max-width:calc(100% - 16px);left:50%;transform:translateX(-50%)}.blossom-hero .wg-canvas{width:440px;max-width:none;left:50%;margin:0;transform:translateX(-50%)}}
/* Preserve reference metrics while preventing fallback-font wrapping from overlapping the next section. */
.blossom-countdown{height:auto;min-height:248px;padding-bottom:37px}
.blossom-schedule{height:auto;min-height:489px;padding-bottom:8px}
.blossom-rsvp{height:auto;min-height:529px;padding-bottom:25px}
.blossom-ending{height:auto;min-height:371px;padding-bottom:28px}
.blossom-ending .blossom-ending-divider,.blossom-ending .blossom-ending-flower{position:relative;top:auto;left:auto;margin:auto}
.blossom-countdown>.blossom-divider,.blossom-schedule>.blossom-divider,.blossom-rsvp>.blossom-divider,.blossom-map-heading>.blossom-divider{position:relative;top:auto;left:auto;margin:1px auto 0}
.blossom-countdown .wg-countdown{margin-top:21px}.blossom-schedule ol{margin-top:35px}.blossom-rsvp :deep(.wg-rsvp){margin-top:29px}
.blossom-map-heading{height:auto;min-height:159px;padding-bottom:21px}

.native-rsvp-panel{position:relative;max-width:560px;margin:28px auto;padding:0 16px;text-align:start}.real-event [data-family-greeting]{overflow-wrap:anywhere}.real-event .native-activity-details{font:15px/1.5 Georgia,serif;grid-column:1/-1}.real-event .native-activity-details a{text-decoration:underline}.real-event ol li{height:auto;min-height:80px;padding-block:12px}.real-event .blossom-schedule{height:auto;padding-bottom:48px}.real-event [data-section="ending"] p{white-space:pre-line;overflow-wrap:anywhere}
</style>
