<script setup lang="ts">
defineProps<{ invitation: any; variant: 'classic' | 'minimal' | 'romantic' }>();
</script>

<template>
    <article class="mx-auto max-w-3xl overflow-hidden rounded-xl bg-white shadow" :class="{ 'border-t-8': variant === 'classic', 'border': variant === 'minimal', 'border-2': variant === 'romantic' }" :style="{ borderColor: invitation.settings.primary_color, color: invitation.settings.secondary_color, fontFamily: invitation.settings.body_font === 'serif' ? 'Georgia, serif' : 'ui-sans-serif, system-ui, sans-serif', textAlign: invitation.settings.text_alignment }">
        <header v-if="invitation.settings.sections.hero" class="p-8 sm:p-12" :style="{ backgroundColor: invitation.settings.primary_color, color: '#ffffff' }">
            <p v-if="invitation.event.event_type" class="text-sm font-medium uppercase tracking-[0.2em]">{{ invitation.event.event_type }}</p>
            <h1 class="mt-3 text-3xl font-semibold sm:text-5xl" :style="{ fontFamily: invitation.settings.heading_font === 'modern_sans' ? 'ui-sans-serif, system-ui, sans-serif' : 'Georgia, serif' }">{{ invitation.event.title }}</h1>
            <p v-if="invitation.party_name" class="mt-5 text-lg">Invitation for {{ invitation.party_name }}</p>
        </header>

        <div class="space-y-8 p-6 sm:p-10">
            <section v-if="invitation.settings.sections.hosts && invitation.event.host_name"><h2 class="text-xl font-semibold">Hosts</h2><p class="mt-2">{{ invitation.event.host_name }}<span v-if="invitation.event.second_host_name"> &amp; {{ invitation.event.second_host_name }}</span></p></section>
            <section v-if="invitation.settings.sections.main_date && invitation.event.main_date"><h2 class="text-xl font-semibold">Date &amp; time</h2><p class="mt-2">{{ invitation.event.main_date }}</p><p v-if="invitation.event.start_time || invitation.event.end_time">{{ invitation.event.start_time || 'Time to be confirmed' }}<span v-if="invitation.event.end_time"> – {{ invitation.event.end_time }}</span></p><p class="mt-1 text-sm opacity-70">{{ invitation.event.timezone }}</p></section>
            <section v-if="invitation.settings.sections.schedule && invitation.event.activities.length"><h2 class="text-xl font-semibold">Schedule</h2><div class="mt-3 space-y-4"><div v-for="(activity, index) in invitation.event.activities" :key="`${activity.title}-${index}`"><h3 class="font-medium">{{ activity.title }}</h3><p class="text-sm">{{ activity.date }} · {{ activity.start_time }}<span v-if="activity.end_time"> – <span v-if="activity.end_date !== activity.date">{{ activity.end_date }}, </span>{{ activity.end_time }}</span></p><p v-if="activity.venue || activity.address" class="text-sm">{{ activity.venue }}<span v-if="activity.address"> · {{ activity.address }}</span></p><p v-if="activity.description" class="mt-1 text-sm">{{ activity.description }}</p><a v-if="activity.location_url" :href="activity.location_url" target="_blank" rel="noopener noreferrer" class="mt-1 inline-block text-sm underline">View location</a></div></div></section>
            <section v-if="invitation.settings.sections.location && (invitation.event.venue || invitation.event.address)"><h2 class="text-xl font-semibold">Location</h2><p class="mt-2">{{ invitation.event.venue }}</p><p v-if="invitation.event.address">{{ invitation.event.address }}</p><a v-if="invitation.event.location_url" :href="invitation.event.location_url" target="_blank" rel="noopener noreferrer" class="mt-1 inline-block underline">View location</a></section>
            <section v-if="invitation.settings.sections.guest_information && (invitation.event.parking_information || invitation.event.transportation_information || invitation.event.guest_information)"><h2 class="text-xl font-semibold">Guest information</h2><p v-if="invitation.event.parking_information" class="mt-2"><strong>Parking:</strong> {{ invitation.event.parking_information }}</p><p v-if="invitation.event.transportation_information" class="mt-2"><strong>Transportation:</strong> {{ invitation.event.transportation_information }}</p><p v-if="invitation.event.guest_information" class="mt-2">{{ invitation.event.guest_information }}</p></section>
            <section v-if="invitation.settings.sections.dress_code && invitation.event.dress_code"><h2 class="text-xl font-semibold">Dress code</h2><p class="mt-2">{{ invitation.event.dress_code }}</p></section>
            <section v-if="invitation.settings.sections.accommodation && invitation.event.accommodation_information"><h2 class="text-xl font-semibold">Accommodation</h2><p class="mt-2">{{ invitation.event.accommodation_information }}</p></section>
            <section v-if="invitation.settings.sections.rsvp" class="rounded-lg p-5" :style="{ backgroundColor: invitation.settings.secondary_color, color: '#ffffff' }"><h2 class="text-xl font-semibold">RSVP</h2><p class="mt-2">{{ invitation.event.rsvp_open ? `Please respond by ${invitation.event.rsvp_deadline || 'the RSVP deadline'}.` : 'RSVP is now closed.' }}</p><p class="mt-3 text-sm opacity-80">RSVP action will use the existing secure invitation link.</p></section>
        </div>
    </article>
</template>
