<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import ReferenceAsset from './ReferenceAsset.vue';
import { useReferenceExperience } from './referenceExperience';

const props = defineProps<{ invitation: any }>();
const root = ref<HTMLElement | null>(null);
const heroVideo = ref<HTMLVideoElement | null>(null);
const letter = ref<HTMLElement | null>(null);
const curtainsOpen = ref(false);
const { names, date, validDate, countdown, enter } = useReferenceExperience(() => props.invitation, root);
const longDate = computed(() => validDate.value ? date.value.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '');
const shortDate = computed(() => validDate.value ? [date.value.getDate(), date.value.getMonth() + 1, date.value.getFullYear()].map(n => String(n).padStart(2, '0')).join(' / ') : '');
const initials = computed(() => [props.invitation.event.host_name, props.invitation.event.second_host_name].filter(Boolean).map(name => name[0]).join(' ♥ '));
const meetings = computed(() => props.invitation.event.activities?.filter((a: any) => a.activity_type === 'meeting_point') || []);
const celebrations = computed(() => props.invitation.event.activities?.filter((a: any) => ['ceremony', 'celebration'].includes(a.activity_type)) || []);
let curtainObserver: IntersectionObserver | undefined;
onMounted(() => {
    if (!matchMedia('(prefers-reduced-motion: reduce)').matches) heroVideo.value?.play().catch(() => { /* Keep the exact poster when autoplay is unavailable. */ });
    curtainObserver = new IntersectionObserver(entries => { curtainsOpen.value = entries[0].isIntersecting; }, { threshold: .2 });
    if (letter.value) curtainObserver.observe(letter.value);
});
onBeforeUnmount(() => { curtainObserver?.disconnect(); heroVideo.value?.pause(); });

const copied = ref<number | null>(null);
const copyFailed = ref(false);
async function copyGift(value: string, index: number) {
    try { await navigator.clipboard.writeText(value); copied.value = index; copyFailed.value = false; }
    catch { copyFailed.value = true; }
}
// This fallback is only a local presentation specimen. Real invitations supply their RSVP slot.
const demoResponse = ref('accepted');
const demoSent = ref(false);
</script>

<template>
<article ref="root" class="reference-document plum-document">
    <section class="plum-page plum-hero">
        <ReferenceAsset v-if="!invitation.media?.heroVideo" background name="Royal Plum arch opening" :src="invitation.media?.heroPoster" />
        <video v-else ref="heroVideo" class="plum-hero-video" :src="invitation.media.heroVideo" :poster="invitation.media.heroPoster" muted playsinline preload="auto"></video>
        <div class="plum-shade"></div>
        <div class="plum-identity">
            <span class="plum-initials" aria-hidden="true">{{ initials }}</span>
            <p class="plum-hero-kicker">A Journey of Love Begins</p>
            <h1><span>{{ invitation.event.host_name }}</span><span v-if="invitation.event.second_host_name" class="plum-amp">&amp;</span><span>{{ invitation.event.second_host_name }}</span></h1>
            <span class="plum-ornament" aria-hidden="true">✦</span><p class="plum-hero-date">{{ shortDate }}</p>
            <p class="plum-copy plum-hero-venue">{{ invitation.event.venue }}<template v-if="invitation.event.start_time"> - {{ invitation.event.start_time }}</template></p>
        </div>
        <button type="button" class="plum-scroll" aria-label="Scroll" @click="enter">Keep scrolling<br />and RSVP<span aria-hidden="true">⌄</span></button>
    </section>

    <section v-if="validDate" class="plum-page plum-countdown-page" data-invitation-content>
        <ReferenceAsset class="plum-countdown-art plum-countdown-left" name="Countdown floral border" :src="invitation.media?.countdownArt" />
        <ReferenceAsset class="plum-countdown-art plum-countdown-right" name="Countdown floral border" :src="invitation.media?.countdownArt" />
        <div class="plum-inner" data-reveal><h2 class="plum-title">Countdown</h2><p class="plum-eyebrow">Until {{ longDate }}</p><div class="plum-countdown"><div v-for="(value, i) in countdown" :key="i"><strong>{{ value }}</strong><span>{{ ['Days','Hours','Minutes','Seconds'][i] }}</span></div></div></div>
    </section>

    <section ref="letter" class="plum-page plum-letter" :class="{ 'curtains-open': curtainsOpen }">
        <ReferenceAsset class="plum-curtain plum-curtain-left" name="Left curtain" :src="invitation.media?.curtainLeft" />
        <ReferenceAsset class="plum-curtain plum-curtain-center" name="Curtain valance" :src="invitation.media?.curtainCenter" />
        <ReferenceAsset class="plum-curtain plum-curtain-right" name="Right curtain" :src="invitation.media?.curtainRight" />
        <div class="plum-inner" data-reveal><h2 class="plum-title">Wedding invitation</h2><p class="plum-copy">{{ invitation.event.description }}</p><div v-if="invitation.reference_demo?.families" class="plum-families"><p v-for="family in invitation.reference_demo.families" :key="family">Mr. &amp; Mrs.{{ family }}</p></div><p class="plum-copy">Request the honor of your presence at the wedding of their son and daughter</p><h2 class="plum-invitation-names">{{ invitation.event.host_name }}<b>&amp;</b>{{ invitation.event.second_host_name }}</h2><p class="plum-eyebrow">{{ longDate }}</p></div>
    </section>

    <section v-if="meetings.length" class="plum-page plum-meeting"><div class="plum-inner" data-reveal><p class="plum-eyebrow">Meeting Point</p><h2 class="plum-title">Where The Day Begins</h2><div class="plum-meeting-grid"><article v-for="(activity,i) in meetings" :key="i" class="plum-card"><p class="plum-eyebrow">{{ activity.title }}</p><h3>{{ activity.venue }}</h3><a v-if="activity.location_url" class="plum-button" :href="activity.location_url" target="_blank" rel="noopener noreferrer">View on map</a></article></div></div></section>

    <section v-if="celebrations.length" class="plum-page plum-events">
        <ReferenceAsset class="plum-event-flower plum-event-flower-top" name="White floral cluster" :src="invitation.media?.flowerCluster" /><ReferenceAsset class="plum-event-flower plum-event-flower-bottom" name="White bouquet" :src="invitation.media?.flowerBouquet" />
        <div class="plum-inner" data-reveal><h2 class="plum-title">The Celebration</h2><ReferenceAsset class="plum-venue-art" name="Ceremony artwork" :src="invitation.media?.ceremonyArt" /><div class="plum-events-grid"><template v-for="(activity,i) in celebrations" :key="i"><ReferenceAsset v-if="i > 0" class="plum-venue-art plum-reception-art" name="Celebration artwork" :src="invitation.media?.celebrationArt" /><article class="plum-card"><p class="plum-eyebrow">{{ activity.title }}</p><h3>{{ activity.venue }}<template v-if="activity.start_time"> - {{ activity.start_time }}</template></h3><a v-if="activity.location_url" class="plum-button" :href="activity.location_url" target="_blank" rel="noopener noreferrer">View on map</a></article></template></div></div>
    </section>

    <section v-if="invitation.event.dress_code" class="plum-page plum-dress"><div class="plum-inner"><ReferenceAsset class="plum-venue-art" name="Dress code illustration" :src="invitation.media?.dressArt" /><h2 class="plum-title">Dress Code</h2><p class="plum-dress-line">{{ invitation.event.dress_code }}</p><p class="plum-dress-note">Please avoid wearing white &amp; black</p></div></section>
    <section v-if="invitation.content?.story_enabled" class="plum-page plum-story"><ReferenceAsset class="plum-static-flower plum-static-flower-top" name="White floral corner" :src="invitation.media?.flowerCluster" /><ReferenceAsset class="plum-static-flower plum-static-flower-bottom" name="White bouquet corner" :src="invitation.media?.flowerBouquet" /><div class="plum-inner"><h2 class="plum-title">{{ invitation.content.story_heading || 'Our Story' }}</h2><ReferenceAsset class="plum-story-photo" name="Anthony and Tina story photo" :src="invitation.media?.storyPhoto" /><p class="plum-story-copy">{{ invitation.content.story_body }}</p></div></section>

    <section v-if="invitation.content?.gift_registry_enabled" class="plum-page plum-gifts">
        <ReferenceAsset class="plum-gift-flower plum-gift-flower-top" name="Gift floral corner" :src="invitation.media?.giftFlowers" /><ReferenceAsset class="plum-gift-flower plum-gift-flower-bottom" name="Gift floral corner" :src="invitation.media?.giftFlowers" />
        <div class="plum-gift-card" data-reveal><h2 class="plum-title">Wedding Gift</h2><p class="plum-copy">{{ invitation.content.gift_registry_intro }}</p><div class="plum-payments"><article v-for="(method,i) in invitation.gift_methods" :key="i"><strong>{{ method.label }}</strong><div><p>{{ method.details }}</p><button type="button" class="plum-copy-button" :aria-label="`Copy ${method.label}`" @click="copyGift(method.details, i)"><span aria-hidden="true">{{ copied === i ? '✓' : '⧉' }}</span><span v-if="copied === i" class="plum-copied" role="status">Copied</span></button></div></article></div><p v-if="copyFailed" role="status">Please select and copy the details.</p></div>
    </section>

    <section class="plum-page plum-rsvp"><div class="plum-inner" data-reveal><p class="plum-eyebrow">Kindly reply</p><h2 class="plum-rsvp-title">RSVP</h2><p class="plum-rsvp-meta">Please reply before: {{ invitation.event.rsvp_deadline }}</p><slot>
        <p class="plum-rsvp-meta">Number of persons: <strong>1</strong></p>
        <form class="plum-demo-form" @submit.prevent="demoSent = true">
            <fieldset class="plum-field"><legend class="plum-label">Are you attending?</legend><div class="plum-options"><label><input v-model="demoResponse" type="radio" name="plum-demo-attendance" value="accepted" required /><span>Joyfully Accept</span></label><label><input v-model="demoResponse" type="radio" name="plum-demo-attendance" value="declined" /><span>Regretfully Decline</span></label></div></fieldset>
            <div class="plum-field"><label for="plum-demo-name" class="plum-label">Names of the people attending:</label><div class="plum-attendee"><span>01</span><input id="plum-demo-name" class="plum-input" placeholder="Your name" autocomplete="name" required /></div></div>
            <div class="plum-field"><label for="plum-demo-note" class="plum-label">Any special requests or notes...</label><textarea id="plum-demo-note" class="plum-input" rows="3" placeholder="Any special requests or notes..."></textarea></div><button class="plum-submit" type="submit">Submit</button>
            <p v-if="demoSent" class="plum-demo-success" role="status">Demo response shown. Nothing was sent or saved.</p>
        </form>
    </slot></div></section>

    <section class="plum-page plum-ending"><ReferenceAsset class="plum-static-flower plum-static-flower-top" name="White floral corner" :src="invitation.media?.flowerCluster" /><ReferenceAsset class="plum-static-flower plum-static-flower-bottom" name="White bouquet corner" :src="invitation.media?.flowerBouquet" /><div class="plum-inner" data-reveal><p class="plum-eyebrow">With gratitude</p><h2>{{ names }}</h2><p class="plum-copy"><br />♡ Happily ever after ♡</p><p class="plum-eyebrow">{{ longDate }}</p></div></section><footer class="plum-footer"><span>FormalEvites</span></footer>
</article>
</template>

<style scoped>
@font-face{font-family:Plum Cormorant;src:url('/fonts/reference/CormorantGaramond-Variable.ttf');font-weight:300 700;font-display:swap}
@font-face{font-family:Plum Inter;src:url('/fonts/reference/Inter-Variable.ttf');font-weight:100 900;font-display:swap}
@font-face{font-family:Plum Italianno;src:url('/fonts/reference/Italianno-Regular.ttf');font-weight:400;font-display:swap}
.plum-document{--plum:#3a1f48;--paper:#faf7f2;--script:'Invitation Script',cursive;background:var(--paper);color:var(--plum);font:16px/1.55 'Plum Cormorant',Georgia,serif;overflow:hidden}
.plum-page{position:relative;isolation:isolate;display:grid;align-items:center;justify-items:center;padding:clamp(80px,10vw,112px) min(5vw,48px);overflow:hidden}.plum-inner,.plum-gift-card{position:relative;width:100%;max-width:672px;z-index:1}.plum-inner{text-align:center}.plum-document [data-reveal]{transform:translateY(24px);transition:opacity .85s cubic-bezier(.22,1,.36,1),transform .85s cubic-bezier(.22,1,.36,1)}.plum-document [data-reveal].arrived{transform:none}
.plum-title{font:400 72px/1 var(--script)}.plum-eyebrow{font:400 11.52px/1.6 'Plum Inter',Arial,sans-serif;letter-spacing:2.88px;text-transform:uppercase;margin-bottom:12px!important}.plum-copy{font-size:clamp(16px,2.2vw,19.2px);line-height:1.7;max-width:592px;margin:19.2px auto 0!important}
.plum-hero{min-height:100svh;color:white;background:black}.plum-hero-video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;z-index:-2}.plum-shade{position:absolute;inset:0;background:#0000004d;z-index:-1}.plum-identity{width:min(100%,576px);text-align:center;animation:plum-enter 1s cubic-bezier(.22,1,.36,1) .15s both}.plum-initials{display:grid;place-items:center;width:72px;height:72px;margin:0 auto 20px;font:11.52px Georgia,serif;letter-spacing:.72px}.plum-hero-kicker{font:11.52px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:3.456px;text-transform:uppercase;margin-bottom:min(5vh,48px)!important}.plum-identity h1{font:400 clamp(70.4px,15vw,116px)/.76 'Plum Cormorant',Georgia,serif}.plum-identity h1>span{display:block}.plum-identity h1 .plum-amp{font-family:'Plum Italianno',cursive;font-size:.4em;margin:.17em 0}.plum-ornament{display:flex;align-items:center;gap:12.8px;width:208px;margin:32px auto 0}.plum-ornament::before,.plum-ornament::after{content:'';height:1px;background:#ffffff73;flex:1}.plum-hero-date{font:12.16px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:3.648px;margin-top:24.8px!important}.plum-hero .plum-hero-venue{font-size:16px;margin-top:16px!important}.plum-scroll{position:absolute;left:50%;bottom:20px;transform:translateX(-50%);display:grid;gap:3.2px;padding:1px 6px;color:white;text-align:center;text-transform:uppercase;font:8.96px/1.5 'Plum Inter',Arial,sans-serif;letter-spacing:2.24px;z-index:6}.plum-scroll>span{font-size:16px;line-height:24px;animation:plum-bob 1.7s ease-in-out infinite}
.plum-countdown-page{min-height:472px}.plum-countdown-page .plum-title{margin-bottom:8.8px}.plum-countdown-art{position:absolute;top:0;height:100%;width:auto;aspect-ratio:630/1920;max-width:none;z-index:0;pointer-events:none}.plum-countdown-left{left:-120px}.plum-countdown-right{right:-120px;transform:scaleX(-1)}.plum-countdown{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;max-width:480px;margin:68px auto 0}.plum-countdown>div{display:grid;justify-items:center}.plum-countdown strong{font:400 clamp(35.2px,7vw,54.4px)/1 var(--script)}.plum-countdown span{font:10.08px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:2.2176px;text-transform:uppercase;margin-top:12px}
.plum-letter{min-height:992px;padding-top:304px}.plum-letter>.plum-inner{max-width:304px;z-index:10}.plum-letter .plum-title{font:67.2px/1 'Plum Italianno',cursive;margin-bottom:37.6px}.plum-curtain{position:absolute;top:2%;width:32%;height:auto;z-index:30;pointer-events:none;max-width:none}.plum-curtain:deep(img){display:block;height:auto;object-fit:contain}.plum-curtain-left{left:-4%;transition:left 1.65s cubic-bezier(.22,1,.36,1);transform-origin:top left}.plum-curtain-right{right:-4%;transition:right 1.65s cubic-bezier(.22,1,.36,1);transform-origin:top right}.plum-curtain-center{top:2.2%;left:50%;width:50%;transform:translateX(-50%);z-index:20}.curtains-open .plum-curtain-left{left:-22%;animation:plum-curtain-left 5s ease-in-out 1.65s infinite}.curtains-open .plum-curtain-right{right:-22%;animation:plum-curtain-right 5s ease-in-out 1.65s infinite}.plum-families{display:grid;gap:5.6px;margin:24px 0 33.6px;font:37.6px/1.2 'Plum Italianno',cursive}.plum-families p+p::before{content:'&';display:block;font-size:.8em;line-height:1.2;margin:3.2px 0}.plum-invitation-names{font:68.8px/1 'Plum Italianno',cursive;margin:32px 0!important}.plum-invitation-names b{font-weight:400;margin:0 .12em}
.plum-meeting{min-height:672px}.plum-meeting-grid,.plum-events-grid{display:grid;gap:16px;margin-top:35.2px}.plum-card{position:relative;padding:clamp(28.8px,5vw,48px);background:#f8f4f1c7;border:1px solid #e5dcda;border-radius:16px}.plum-card .plum-eyebrow{color:#6f596f;margin:8.8px 0 0!important}.plum-card h3{font:59.2px/1 var(--script);margin:2.4px 0}.plum-button{display:inline-flex;justify-content:center;align-items:center;margin-top:19.2px;padding:12px 23.2px;border:1px solid var(--plum);border-radius:999px;font:10.88px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:1.7408px;text-transform:uppercase;color:var(--plum);min-height:43.2px}.plum-button:hover{background:#3a1f480d}
.plum-events{min-height:976px}.plum-events-grid{grid-template-columns:1fr 1fr;position:relative;z-index:1}.plum-events-grid .plum-card{padding-top:64px}.plum-venue-art{position:relative;width:min(70%,288px);height:224px;margin:32px auto 10px;z-index:2;filter:drop-shadow(0 8px 10px #3a1f4814)}.plum-venue-art:deep(img){object-fit:contain}.plum-reception-art{height:auto;aspect-ratio:362/255;align-self:start;justify-self:center;margin:32px 0 10px}.plum-event-flower{position:absolute;width:clamp(160px,20vw,240px);height:auto;z-index:0;pointer-events:none;animation:plum-float 7s ease-in-out infinite}.plum-event-flower:deep(img),.plum-gift-flower:deep(img){height:auto;display:block}.plum-event-flower-top{top:4px;left:-48px}.plum-event-flower-bottom{bottom:4px;right:8px;animation-duration:8s;animation-delay:1.2s}
.plum-dress{min-height:384px;color:#5b365e}.plum-dress .plum-inner{padding-bottom:14.08px}.plum-dress .plum-title,.plum-story .plum-title{margin-bottom:38px;color:var(--plum)}.plum-dress-line{font:clamp(26.4px,5vw,43.2px)/1.25 var(--script);color:#81506f;margin-bottom:14px!important}.plum-dress-note{font:14.08px/1.8 'Plum Cormorant',Georgia,serif;letter-spacing:1.1264px;margin:19.2px auto 0!important}.plum-story{min-height:100svh;color:#5b365e}.plum-story-photo{width:min(100%,480px);height:600px;margin:0 auto clamp(22px,5vw,40px)}.plum-story-photo:deep(img){object-fit:cover}.plum-static-flower{position:absolute;pointer-events:none;z-index:0;opacity:.75}.plum-static-flower:deep(img){display:block;height:auto}.plum-static-flower-top{width:clamp(160px,22vw,240px);left:-48px;top:16px}.plum-static-flower-bottom{width:clamp(176px,24vw,256px);right:-48px;bottom:-24px}.plum-ending .plum-static-flower{opacity:.8}.plum-ending .plum-static-flower-top{top:0}.plum-ending .plum-static-flower-bottom{bottom:0}.plum-story-copy{font-size:19.2px;line-height:1.8;max-width:620px;margin:19.2px auto!important;white-space:pre-line}
.plum-gifts{min-height:544px}.plum-gift-card{background:#f8f4f1b3;border:1px solid #e5dcda;border-radius:16px;padding:clamp(40px,7vw,64px) clamp(24px,6vw,56px);text-align:start}.plum-gift-flower{position:absolute;width:clamp(144px,16vw,192px);height:auto;z-index:2;pointer-events:none;animation:plum-float 5s ease-in-out infinite}.plum-gift-flower-top{top:0;left:calc(50% - 400px)}.plum-gift-flower-bottom{bottom:32px;right:calc(50% - 400px);animation-delay:1.5s}.plum-gift-card>.plum-copy,.plum-ending .plum-copy{color:#6f596f}.plum-payments{display:grid;gap:12px;margin-top:25.6px}.plum-payments article{padding:16px;border:1px solid #31163a29;border-radius:12px}.plum-payments strong{display:block;font-weight:700}.plum-payments article>div{display:flex;gap:10.4px;align-items:start;margin-top:4px}.plum-payments article p{flex:1;overflow-wrap:anywhere}.plum-copy-button{position:relative;display:flex;align-items:center;justify-content:center;width:36px;height:36px;flex-shrink:0;border:1px solid #3a1f4833;border-radius:50%;background:white;font:18px Georgia,serif}.plum-copied{position:absolute;bottom:calc(100% + 3px);font:9.92px/1 'Plum Inter',Arial,sans-serif;padding:4.48px 7.2px;background:var(--plum);color:white;border-radius:4px}
.plum-rsvp{min-height:912px}.plum-rsvp-title{font:96px/1 var(--script);margin-bottom:4px!important}.plum-rsvp-meta{margin-bottom:24px!important}.plum-demo-form{max-width:608px;margin:auto;padding:32px;border:1px solid #3a1f4821;border-radius:16px;background:#ffffffb3;text-align:start}.plum-field{margin:16px 0 0;padding:0;min-width:0;border:0}.plum-label{display:block;float:none;width:100%;font:650 10.72px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:.8576px;text-transform:uppercase;margin-bottom:6.4px}.plum-options{display:grid;grid-template-columns:1fr 1fr;gap:10.4px}.plum-options label{position:relative;display:block;min-height:48px}.plum-options input{position:absolute;opacity:0}.plum-options span{display:flex;align-items:center;justify-content:center;min-height:48px;border:1px solid #321b3a33;border-radius:10.4px;background:#ffffffb8}.plum-options input:checked+span{color:var(--paper);background:var(--plum);border-color:var(--plum)}.plum-options input:focus-visible+span{outline:2px solid var(--plum);outline-offset:3px}.plum-attendee{display:grid;grid-template-columns:27.2px 1fr;gap:10.4px;margin-top:12px}.plum-attendee>span{color:#b89a68;font:10.88px/1.55 'Plum Inter',Arial,sans-serif;padding-top:13.6px;letter-spacing:1.2px}.plum-input{width:100%;min-height:52px;border:1px solid #321b3a33;border-radius:10.4px;background:#ffffffb8;padding:12px 14.4px;font:16px/1.55 'Plum Cormorant',Georgia,serif;color:var(--plum)}textarea.plum-input{display:inline-block;vertical-align:baseline;min-height:100.4px;resize:vertical}.plum-submit{margin-top:17.6px;width:100%;min-height:52px;background:var(--plum);color:white;border-radius:999px;font:700 11.52px/1.55 'Plum Inter',Arial,sans-serif;letter-spacing:1.6128px;text-transform:uppercase}.plum-demo-success{margin-top:16px!important}
.plum-ending{min-height:320px}.plum-ending h2{font:88px/1 var(--script)}.plum-footer{height:88px;display:flex;align-items:center;justify-content:center;background:var(--plum);padding:16px}.plum-footer>a{display:block}.plum-footer :deep(.reference-asset){width:128px;height:47.52px;opacity:.78;filter:brightness(0) invert(1)}.plum-footer :deep(img){object-fit:contain}
@media(max-width:1000px){.plum-letter{padding:208px 5vw 80px}.plum-letter .plum-title{font-size:60.8px}.plum-card h3{font-size:53.76px}}
@media(max-width:600px){.plum-page{padding:80px 20px}.plum-title{font-size:53.6px}.plum-copy{font-size:16px}.plum-identity h1{font-size:70.4px}.plum-countdown{max-width:none;gap:7.2px;margin-top:52px}.plum-countdown strong{font-size:35.2px}.plum-countdown span{font-size:7.68px;letter-spacing:.9984px}.plum-countdown-left{left:-128px}.plum-countdown-right{right:-128px}.plum-letter{min-height:928px;padding-top:192px}.plum-letter .plum-title{font-size:51.2px}.plum-curtain-left,.plum-curtain-right{width:50%}.plum-curtain-center{width:68%}.plum-families{font-size:28.8px}.plum-invitation-names{font-size:50.4px}.plum-card{padding:28.8px}.plum-card h3{font-size:41.6px}.plum-events-grid{grid-template-columns:1fr}.plum-event-flower{width:160px}.plum-story-photo{width:min(100%,330px);height:auto;aspect-ratio:330/405.12;margin-bottom:22px}.plum-story-copy{font-size:15.36px;line-height:1.65;margin:15.36px auto!important}.plum-dress .plum-title,.plum-story .plum-title{margin-bottom:20px}.plum-dress-line{font-size:26.4px}.plum-dress-note{margin-top:15.36px!important}.plum-gift-card{padding:40px 24px}.plum-gift-flower{width:144px}.plum-gift-flower-top{left:-40px}.plum-gift-flower-bottom{right:-40px}.plum-rsvp-title{font-size:72px}.plum-demo-form{padding:16px}.plum-options{grid-template-columns:1fr}.plum-ending h2{font-size:60.8px}}
@keyframes plum-enter{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@keyframes plum-bob{50%{transform:translateY(6px)}}@keyframes plum-float{25%{transform:translate(2px,-4px)}50%{transform:translate(-2px,-2px)}75%{transform:translate(1px,-5px)}}@keyframes plum-curtain-left{50%{transform:rotate(-1.5deg) translate(4px,-3px)}}@keyframes plum-curtain-right{50%{transform:rotate(1.5deg) translate(-4px,-3px)}}
@media(prefers-reduced-motion:reduce){.plum-document [data-reveal]{transform:none}.plum-curtain-left{left:-22%}.plum-curtain-right{right:-22%}}
</style>
