<script setup lang="ts">
import { computed, ref } from 'vue';
import ReferenceAsset from './ReferenceAsset.vue';
import DemoEnvelope from './DemoEnvelope.vue';
import WebgencyRsvpDemo from './WebgencyRsvpDemo.vue';
import { useReferenceExperience } from './referenceExperience';
import './webgencyDemos.css';
import NativeEventSections from './NativeEventSections.vue';
import { familyGreeting, invitationText } from './invitationText';
import { webgencyEventContent } from './webgencyEventContent';
const props = defineProps<{ invitation: any }>();
const invitation = computed(() => webgencyEventContent(props.invitation, 'sacred'));
const realRsvpOpen = ref(false);
const t = (text: string) => invitationText(props.invitation, text);
const root = ref<HTMLElement | null>(null);
const rsvp = ref<InstanceType<typeof WebgencyRsvpDemo> | null>(null);
const { countdown, enter } = useReferenceExperience(() => props.invitation, root);
const media = computed(() => props.invitation.media || {});
</script>
<template>
    <article ref="root" class="webgency-demo sacred-demo" :class="{ 'real-event': !invitation.reference_demo }">
        <DemoEnvelope v-if="invitation.reference_demo || media.envelope" :image="media.envelope" :video="media.envelopeVideo" name="Embossed white floral envelope · R & Z burgundy seal" :label="t('Tap to open')" />
        <header class="wg-section sacred-hero"><div class="wg-canvas">
            <video v-if="media.heroVideo" :src="media.heroVideo" :poster="media.heroPoster" autoplay muted playsinline loop aria-hidden="true" />
            <ReferenceAsset v-else class="wg-photo sacred-hero-media" name="Swans2 · garden swan animation" :src="media.heroPoster" />
            <div class="sacred-glow" aria-hidden="true"></div><p class="sacred-wedding-day wg-script">{{ t('Wedding Day') }}</p><p class="sacred-date">{{ invitation.event.date_label }}</p>
            <h1 class="wg-script"><span>{{ invitation.event.host_name }}</span><small>&amp;</small><span>{{ invitation.event.second_host_name }}</span></h1>
            <button type="button" class="sacred-scroll wg-script" @click="enter">{{ t('Scroll down') }}<span aria-hidden="true">⌄</span></button>
            <ReferenceAsset class="wg-art sacred-left-flowers" name="Left garden floral arrangement" :src="media.heroLeft" /><ReferenceAsset class="wg-art sacred-right-flowers" name="Right garden floral arrangement" :src="media.heroRight" />
            <ReferenceAsset class="wg-art sacred-paper" name="Garden paper backdrop" :src="media.paper" /><ReferenceAsset class="wg-art sacred-calligraphy" name="Garden Arabic calligraphy" :src="media.calligraphy" />
            <div class="sacred-introduction" data-invitation-content><h2 class="wg-script"><span v-for="line in invitation.content.blessing" :key="line">{{ line }}</span></h2><p class="wg-body"><strong data-family-greeting>{{ familyGreeting(invitation) }}</strong><br />{{ invitation.content.introduction }}</p></div>
        </div></header>
        <section class="wg-section sacred-countdown"><h2 class="wg-heading">{{ t('The Celebration Begins In') }}</h2><div class="wg-countdown" dir="ltr"><template v-for="(value,i) in countdown" :key="i"><span v-if="i" aria-hidden="true">:</span><div><strong>{{ value }}</strong><small>{{ t(['Days','Hours','Minutes','Seconds'][i]) }}</small></div></template></div></section>
        <section class="wg-section sacred-schedule"><h2 class="wg-heading">{{ t('Schedule of Events') }}</h2><ReferenceAsset class="wg-art sacred-title-left" name="left-element_1 · heading flourish" :src="media.flourishLeft" /><ReferenceAsset class="wg-art sacred-title-right" name="right-element_1 · heading flourish" :src="media.flourishRight" /><ReferenceAsset class="wg-art sacred-schedule-top" name="Schedule upper paper artwork" :src="media.scheduleTop" /><ReferenceAsset class="wg-art sacred-schedule-bottom" name="Schedule lower paper artwork" :src="media.scheduleBottom" /><ol><li v-for="(activity,i) in invitation.event.activities" :key="i"><time>{{ activity.start_time }}</time><p data-reveal>{{ activity.title }}</p><div v-if="!invitation.reference_demo" class="native-activity-details"><p>{{ activity.venue }}</p><p>{{ activity.address }}</p><p>{{ activity.description }}</p><a v-if="activity.location_url" :href="activity.location_url" target="_blank" rel="noopener noreferrer">{{ t('Directions') }}</a></div></li><ReferenceAsset class="wg-art sacred-timeline-rose" name="rose · schedule flower" :src="media.timelineRose" /></ol></section>
        <section class="wg-section sacred-venue"><h2 class="wg-heading">{{ t('Location') }}</h2><ReferenceAsset class="wg-art sacred-venue-divider" name="acomm-decor · venue divider" :src="media.venueDivider" /><h3>{{ invitation.event.venue }}</h3><p class="wg-body">{{ t('Address:') }} {{ invitation.event.address }}</p><ReferenceAsset class="wg-art sacred-venue-art" name="Islamic Center of Melville illustration" :src="media.venueArt" /><ReferenceAsset v-for="i in 6" :key="i" :class="`wg-art sacred-butterfly sacred-butterfly-${i}`" :name="`Venue butterfly ${i}`" :src="media[`butterfly${i}`]" /></section>
        <div v-if="invitation.event.map_url" class="wg-map"><iframe :src="invitation.event.map_url" :title="`Map: ${invitation.event.venue}`" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><ReferenceAsset class="wg-art" name="Rectangle_270 · garden map frame" :src="media.mapFrame" /><ReferenceAsset class="wg-art sacred-map-top" name="Map upper floral border" :src="media.mapTop" /><ReferenceAsset class="wg-art sacred-map-bottom" name="Map lower floral border" :src="media.mapBottom" /></div>
        <section v-if="invitation.reference_demo || invitation.event.dress_code" class="wg-section sacred-preferences"><ReferenceAsset class="wg-art sacred-preference-paper" name="Dress and gift paper artwork" :src="media.preferencePaper" /><ReferenceAsset class="wg-art sacred-preference-right" name="Dress code right botanical artwork" :src="media.preferenceRight" /><ReferenceAsset class="wg-art sacred-preference-left" name="Gift left botanical artwork" :src="media.preferenceLeft" /><h2 class="wg-heading">{{ t('Dress Code') }}</h2><p class="wg-body">{{ invitation.content.dress_intro }}</p><template v-if="invitation.reference_demo"><h2 class="wg-heading">Gift Preference</h2><p class="wg-body">{{ invitation.content.gift_intro }}</p></template></section>
        <NativeEventSections :invitation="invitation" /><section class="wg-section sacred-rsvp" data-section="rsvp"><h2 class="wg-heading">{{ t('Confirm Your Attendance') }}</h2><p class="wg-body">{{ t('To help us prepare for a joyful celebration, kindly confirm your attendance.') }}</p><button type="button" aria-label="Open RSVP" aria-haspopup="dialog" @click="invitation.reference_demo ? rsvp?.open() : realRsvpOpen = !realRsvpOpen"><ReferenceAsset name="wax_seal_1 · burgundy RSVP seal" :src="media.rsvpSeal" /><span aria-hidden="true">⌄</span><span class="wg-script">{{ t('Click to open') }}</span></button><div v-if="!invitation.reference_demo && realRsvpOpen" class="native-rsvp-panel"><slot /></div></section>
        <footer v-if="invitation.content?.ending_enabled !== false" class="wg-section sacred-ending" data-section="ending"><div class="wg-canvas"><ReferenceAsset class="wg-photo" name="Closing couple photograph · pexels-vinicius-quar" :src="media.endingPhoto" /><div class="sacred-ending-fade" aria-hidden="true"></div><h2 class="wg-heading">{{ invitation.content?.ending_title || t('Hope to see you there!') }}</h2><p>{{ invitation.content?.ending_message || [invitation.event.host_name, invitation.event.second_host_name].filter(Boolean).join(' & ') }}</p><ReferenceAsset class="wg-art sacred-ending-paper" name="Ending paper texture" :src="media.endingPaper" /></div></footer>
        <WebgencyRsvpDemo v-if="invitation.reference_demo" ref="rsvp" theme="sacred" :deadline="invitation.event.rsvp_deadline" />
    </article>
</template>
<style scoped>
.sacred-demo{--wg-canvas:450px;--wg-paper:#f9f0e0;--wg-accent:#a67d2b;--wg-ink:#6c513f}.sacred-hero,.sacred-hero .wg-canvas{height:1240px}.sacred-hero-media,.sacred-hero video{position:absolute;top:0;width:100%;height:800px}.sacred-glow{position:absolute;top:0;width:100%;height:676px;background:radial-gradient(circle,#fff9eb,transparent 85%)}.sacred-wedding-day{position:absolute;top:144px;left:0;right:0;font-size:40px;line-height:50px;color:#a67d2b}.sacred-date{position:absolute;top:196px;left:0;right:0;font:25px/37px Georgia,serif;color:#a67d2b}.sacred-hero h1{position:absolute;top:280px;left:0;right:0;font-size:80px;line-height:80px;color:#a67d2b}.sacred-hero h1>span{display:block}.sacred-hero h1 small{display:block;font-size:40px;line-height:40px;color:#a07b33}.sacred-scroll{position:absolute;top:510px;left:calc(50% - 100px);width:200px;font-size:32px;line-height:35px;color:#a67d2b;background:transparent;border:0;cursor:pointer}.sacred-scroll span{display:block;font:25px/30px Georgia,serif}.sacred-left-flowers{width:241px;height:361px;top:557px;left:-24px}.sacred-right-flowers{width:250px;height:373px;top:540px;right:-23px}.sacred-paper{width:744px;height:487px;top:753px;left:calc(50% - 372px)}.sacred-calligraphy{width:283px;height:86px;top:813px;left:calc(50% - 141px)}.sacred-introduction{position:absolute;top:899px;left:0;right:0;scroll-margin-top:20px}.sacred-introduction h2{font-size:41px;line-height:43px;color:#a67d2b}.sacred-introduction h2 span{display:block}.sacred-introduction .wg-body{width:307px;margin-top:22px;font:21px/26px Georgia,serif;color:#6a5140}.sacred-introduction strong{font-weight:400}
.sacred-countdown{height:257px;padding-top:28px}.sacred-countdown .wg-countdown{margin-top:28px}.sacred-schedule{height:570px;padding-top:45px}.sacred-title-left{width:79px;height:40px;left:calc(50% - 204px);top:56px}.sacred-title-right{width:78px;height:39px;left:calc(50% + 125px);top:56px}.sacred-schedule-top{width:744px;height:346px;left:calc(50% - 372px);top:-20px}.sacred-schedule-bottom{width:744px;height:259px;left:calc(50% - 372px);top:321px}.sacred-schedule ol{position:relative;list-style:none;width:300px;max-width:calc(100% - 32px);margin:24px auto 0;padding:0}.sacred-schedule ol:before{content:'';position:absolute;left:calc(50% - 1px);top:27px;height:321px;width:2px;background:#8c7666}.sacred-schedule li{position:relative;height:80px;display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center}.sacred-schedule li:after{content:'';position:absolute;top:27px;left:calc(50% - 5.5px);width:11px;height:11px;border-radius:50%;background:#8c7666}.sacred-schedule time{font:30px/47px Georgia,serif;color:#846f61}.sacred-schedule li p{font:20px/22px Georgia,serif}.sacred-timeline-rose{width:73px;height:72px;top:-4px;left:calc(50% - 36px);z-index:2!important}
.sacred-venue{height:421px;padding-top:28px}.sacred-venue-divider{width:96px;height:29px;left:calc(50% - 48px);top:81px}.sacred-venue h3{font:20px/31px Georgia,serif;margin-top:19px}.sacred-venue .wg-body{width:308px;margin-top:7px;font:17px/21px Georgia,serif}.sacred-venue-art{width:380px;max-width:100%;height:247px;left:50%;transform:translateX(-50%);top:174px}.sacred-butterfly{width:42px;height:34px;animation:sacred-drift 6s ease-in-out infinite alternate}.sacred-butterfly-1{left:calc(50% + 135px);top:20px}.sacred-butterfly-2{left:calc(50% - 137px);top:2px;width:55px;height:53px;animation-delay:-2s}.sacred-butterfly-3{left:calc(50% - 198px);top:117px;animation-delay:-3s}.sacred-butterfly-4{left:calc(50% + 167px);top:144px;animation-delay:-1s}.sacred-butterfly-5{left:calc(50% - 175px);top:260px;animation-delay:-4s}.sacred-butterfly-6{left:calc(50% + 90px);top:284px;animation-delay:-2s}
.sacred-demo .wg-map .sacred-map-top{width:190px;height:43px;inset:-26px auto auto calc(50% - 95px)}.sacred-demo .wg-map .sacred-map-bottom{width:190px;height:38px;inset:auto auto -23px calc(50% - 95px)}.sacred-preferences{height:491px;padding-top:86px}.sacred-preferences .wg-body{width:310px;font:21px/26px Georgia,serif;margin-top:13px}.sacred-preferences .wg-body+.wg-heading{margin-top:43px}.sacred-preference-paper{width:744px;height:453px;left:calc(50% - 372px);top:20px}.sacred-preference-right{width:305px;height:397px;left:calc(50% + 58px);top:9px}.sacred-preference-left{width:255px;height:267px;left:calc(50% - 297px);top:250px}
.sacred-rsvp{height:438px;padding-top:51px}.sacred-rsvp>.wg-body{width:372px;font:21px/26px Georgia,serif;margin-top:20px}.sacred-rsvp>button{width:224px;border:0;background:transparent;padding:0;margin-top:23px;color:#a67d2b;cursor:pointer}.sacred-rsvp button .reference-asset{width:190px;height:133px;margin:auto;background:transparent}.sacred-rsvp button .reference-asset--missing{outline:1px dashed #99856c55}.sacred-rsvp button>span:not(.reference-asset){display:block;margin-top:15px;font-size:25px;line-height:28px}.sacred-rsvp button>span.wg-script{font-size:32px;line-height:50px;margin-top:0}
.sacred-ending,.sacred-ending .wg-canvas{height:673px}.sacred-ending .wg-photo{position:absolute;inset:0;width:100%;height:675px}.sacred-ending-fade{position:absolute;inset:0 0 auto;height:237px;background:linear-gradient(#f9f0e0,transparent)}.sacred-ending h2{position:absolute;top:12px;left:0;right:0}.sacred-ending p{position:absolute;top:73px;left:0;right:0;font:28px/45px Georgia,serif;color:#a67d2b}.sacred-ending-paper{width:537px;height:537px;left:calc(50% - 268px);top:173px}
@keyframes sacred-drift{to{transform:translate(3px,-8px) rotate(3deg)}}
.sacred-hero .sacred-paper{z-index:0}.sacred-hero :is(.sacred-left-flowers,.sacred-right-flowers,.sacred-calligraphy){z-index:1}
@media(max-width:600px){.sacred-countdown{height:247px}.sacred-venue{height:405px}.sacred-countdown .wg-countdown{gap:5px}.sacred-countdown .wg-countdown strong{font-size:29px}.sacred-rsvp>.wg-body{font-size:20px}.sacred-title-left{left:4px}.sacred-title-right{left:auto;right:4px}}
.sacred-countdown{height:auto;min-height:257px;padding-bottom:62px}
.sacred-schedule{height:auto;min-height:570px;padding-bottom:37px}
.sacred-rsvp{height:auto;min-height:438px;padding-bottom:1px}
@media(max-width:600px){.sacred-countdown{min-height:247px;padding-bottom:52px}}

.native-rsvp-panel{position:relative;max-width:560px;margin:28px auto;padding:0 16px;text-align:start}.real-event [data-family-greeting]{overflow-wrap:anywhere}.real-event .native-activity-details{font:15px/1.5 Georgia,serif;grid-column:1/-1}.real-event .native-activity-details a{text-decoration:underline}.real-event ol li{height:auto;min-height:80px;padding-block:12px}.real-event .sacred-schedule{height:auto;padding-bottom:48px}.real-event [data-section="ending"] p{white-space:pre-line;overflow-wrap:anywhere}
</style>
