<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Event;
use App\Models\EventPackage;
use App\Models\Payment;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Inertia\Inertia;
use Inertia\Response;

class AdminController extends Controller
{
    public function customers(Request $request): Response { $search = $request->string('search')->trim()->toString(); $customers = Customer::query()->withCount(['users', 'events'])->when($search, fn ($query) => $query->where(fn ($query) => $query->where('name', 'like', "%{$search}%")->orWhere('email', 'like', "%{$search}%")->orWhere('phone', 'like', "%{$search}%")))->latest()->get(); return Inertia::render('Admin/Customers', ['customers' => $customers, 'filters' => ['search' => $search]]); }
    public function storeCustomer(Request $r): RedirectResponse { Customer::create($r->validate(['name'=>'required|string|max:255','contact_name'=>'nullable|string|max:255','email'=>'nullable|email','phone'=>'nullable|string|max:50','is_active'=>'boolean'])); return back()->with('success','Customer created.'); }
    public function updateCustomer(Request $r, Customer $customer): RedirectResponse { $customer->update($r->validate(['name'=>'required|string|max:255','contact_name'=>'nullable|string|max:255','email'=>'nullable|email','phone'=>'nullable|string|max:50','is_active'=>'boolean'])); return back()->with('success','Customer updated.'); }
    public function users(Request $request): Response { $search = $request->string('search')->trim()->toString(); $users = User::with('customer')->where('role','customer')->when($search, fn ($query) => $query->where(fn ($query) => $query->where('name', 'like', "%{$search}%")->orWhere('email', 'like', "%{$search}%")->orWhereHas('customer', fn ($customer) => $customer->where('name', 'like', "%{$search}%"))))->latest()->get(); return Inertia::render('Admin/Users', ['users'=>$users, 'customers'=>Customer::where('is_active',true)->get(), 'filters' => ['search' => $search]]); }
    public function storeUser(Request $r): RedirectResponse { $data=$r->validate(['customer_id'=>'required|exists:customers,id','name'=>'required|string|max:255','email'=>'required|email|unique:users,email','password'=>'required|string|min:8']); User::create([...$data,'role'=>'customer','password'=>Hash::make($data['password'])]); return back()->with('success','Customer user created.'); }
    public function packages(Request $request): Response { $search = $request->string('search')->trim()->toString(); $active = $request->string('active')->toString(); $packages = EventPackage::query()->when($search, fn ($query) => $query->where('name', 'like', "%{$search}%"))->when(in_array($active, ['active', 'inactive'], true), fn ($query) => $query->where('is_active', $active === 'active'))->capacityOrder()->get(); return Inertia::render('Admin/Packages', ['packages'=>$packages, 'filters' => ['search' => $search, 'active' => $active]]); }
    public function storePackage(Request $r): RedirectResponse { EventPackage::create($r->validate(['name'=>'required|string|max:255','minimum_guests'=>'required|integer|min:1','maximum_guests'=>'required|integer|gte:minimum_guests','price'=>'nullable|numeric|min:0','is_active'=>'boolean'])); return back()->with('success','Package created.'); }
    public function updatePackage(Request $r, EventPackage $package): RedirectResponse { $package->update($r->validate(['name'=>'required|string|max:255','minimum_guests'=>'required|integer|min:1','maximum_guests'=>'required|integer|gte:minimum_guests','price'=>'nullable|numeric|min:0','is_active'=>'boolean'])); return back()->with('success','Package updated.'); }
    public function payments(Request $request): Response { $search = $request->string('search')->trim()->toString(); $status = $request->string('status')->toString(); $customerId = $request->integer('customer_id'); $payments = Payment::with(['customer','event','package'])->when($search, fn ($query) => $query->where(fn ($query) => $query->where('reference', 'like', "%{$search}%")->orWhereHas('customer', fn ($customer) => $customer->where('name', 'like', "%{$search}%"))->orWhereHas('event', fn ($event) => $event->where('title', 'like', "%{$search}%"))))->when($status, fn ($query) => $query->where('status', $status))->when($customerId, fn ($query) => $query->where('customer_id', $customerId))->latest()->get(); $summary = ['total_final_amount' => $payments->sum(fn ($payment) => (float) $payment->final_amount), 'total_paid_amount' => $payments->sum(fn ($payment) => (float) $payment->paid_amount), 'total_remaining_amount' => $payments->sum(fn ($payment) => max((float) $payment->final_amount - (float) $payment->paid_amount, 0)), 'pending_count' => $payments->where('status', 'pending')->count(), 'confirmed_count' => $payments->where('status', 'confirmed')->count()]; return Inertia::render('Admin/Payments', ['payments'=>$payments, 'summary'=>$summary, 'customers'=>Customer::where('is_active',true)->get(), 'events'=>Event::with('customer')->latest()->get(), 'packages'=>EventPackage::where('is_active',true)->capacityOrder()->get(), 'filters' => ['search' => $search, 'status' => $status, 'customer_id' => $customerId ?: '']]); }
    public function storePayment(Request $r): RedirectResponse { $data=$r->validate(['customer_id'=>'required|exists:customers,id','event_id'=>'nullable|exists:events,id','event_package_id'=>'nullable|exists:event_packages,id','original_amount'=>'required|numeric|min:0','discount'=>'nullable|numeric|min:0','paid_amount'=>'nullable|numeric|min:0','payment_method'=>'nullable|string|max:100','reference'=>'nullable|string|max:255','payment_date'=>'nullable|date','notes'=>'nullable|string']); $data['discount']=$data['discount']??0; $data['paid_amount']=$data['paid_amount']??0; $data['final_amount']=$data['original_amount']-$data['discount']; $data['status']='pending'; Payment::create($data); return back()->with('success','Manual payment recorded.'); }
    public function confirmPayment(Payment $payment): RedirectResponse { $payment->update(['status'=>'confirmed']); return back()->with('success','Payment confirmed.'); }
}
