<?php
namespace App\Http\Controllers;
use App\Models\Event; use App\Models\EventMealOption; use App\Models\InvitationParty; use App\Models\Rsvp; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Inertia\Inertia; use Inertia\Response;
class RsvpController extends Controller {
 public function index(Request $request, Event $event): Response { $this->view($request,$event); $search=$request->string('search')->trim()->toString(); $status=$request->string('status')->toString(); $parties=$event->invitationParties()->with(['rsvp.personResponses'])->when($search,fn($q)=>$q->where('name','like',"%{$search}%"))->when(in_array($status,Rsvp::STATUSES,true),fn($q)=>$q->whereHas('rsvp',fn($r)=>$r->where('status',$status)))->orderBy('name')->get(); $all=$event->invitationParties()->with('rsvp.personResponses')->get(); $responses=$all->pluck('rsvp'); $people=$responses->flatMap(fn($r)=>$r?->personResponses ?? collect())->where('is_attending',true); return Inertia::render('Events/Rsvps/Index',['event'=>$event,'parties'=>$parties->map(fn($party)=>$this->partyForPresentation($party))->values(),'summary'=>['party_count'=>$all->count(),'responded'=>$responses->filter(fn($r)=>$r && $r->status!=='pending')->count(),'pending'=>$responses->filter(fn($r)=>!$r || $r->status==='pending')->count(),'attending_parties'=>$responses->where('status','attending')->count(),'declined_parties'=>$responses->where('status','not_attending')->count(),'attending_people'=>$people->count(),'adults'=>$people->where('member_type','adult')->count(),'children'=>$people->where('member_type','child')->count()],'meals'=>$event->mealOptions()->orderBy('display_order')->get(),'filters'=>['search'=>$search,'status'=>$status],'canManage'=>$request->user()->can('update',$event)]); }
 public function show(Request $request, Event $event, InvitationParty $party): Response { $this->view($request,$event); $party=$this->party($event,$party)->load(['rsvp.personResponses.mealOption','members']); return Inertia::render('Events/Rsvps/Show',['event'=>$event,'party'=>$this->partyForPresentation($party)]); }
 public function storeMeal(Request $request, Event $event): RedirectResponse { $this->manage($request,$event); $data=$request->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'display_order'=>['nullable','integer','min:0']]); $event->mealOptions()->create([...$data,'is_active'=>true,'display_order'=>$data['display_order']??0]); return back()->with('success','Meal option added.'); }
 public function updateMeal(Request $request, Event $event, EventMealOption $meal): RedirectResponse { $this->manage($request,$event); abort_unless($meal->event_id===$event->id,404); $data=$request->validate(['name'=>['required','string','max:255'],'description'=>['nullable','string'],'display_order'=>['nullable','integer','min:0']]); $meal->update($data); return back()->with('success','Meal option updated.'); }
 public function setMealActive(Request $request, Event $event, EventMealOption $meal): RedirectResponse { $this->manage($request,$event); abort_unless($meal->event_id===$event->id,404); $data=$request->validate(['is_active'=>['required','boolean']]); $meal->update($data); return back()->with('success',$data['is_active']?'Meal option activated.':'Meal option deactivated.'); }
 public function regenerateToken(Request $request, Event $event, InvitationParty $party): RedirectResponse { $this->manage($request,$event); $party=$this->party($event,$party); do { $token=Str::random(64); } while (InvitationParty::where('rsvp_token',$token)->exists()); $party->update(['rsvp_token'=>$token]); return back()->with('success','A new RSVP link was generated.'); }
 private function view(Request $r,Event $e):void { abort_unless($r->user()->can('view',$e),403); } private function manage(Request $r,Event $e):void { abort_unless($r->user()->can('update',$e),403); } private function party(Event $e,InvitationParty $p):InvitationParty { abort_unless($p->event_id===$e->id,404); return $p; } private function partyForPresentation(InvitationParty $party): array { $rsvp=$party->rsvp; return ['id'=>$party->id,'name'=>$party->name,'maximum_party_size'=>$party->maximum_party_size,'rsvp'=>$rsvp ? ['status'=>$rsvp->status,'guest_message'=>$rsvp->guest_message,'submitted_at'=>$this->dateTime($rsvp->submitted_at),'last_updated_at'=>$rsvp->submitted_at && $rsvp->last_updated_at && $rsvp->submitted_at->isSameSecond($rsvp->last_updated_at) ? null : $this->dateTime($rsvp->last_updated_at),'person_responses'=>$rsvp->personResponses->map(fn($person)=>['id'=>$person->id,'first_name'=>$person->first_name,'last_name'=>$person->last_name,'member_type'=>$person->member_type,'is_original_party_member'=>$person->is_original_party_member,'is_attending'=>$person->is_attending,'dietary_note'=>$person->dietary_note,'meal_option'=>$person->relationLoaded('mealOption') && $person->mealOption ? ['name'=>$person->mealOption->name] : null])->values()] : null]; } private function dateTime(?\DateTimeInterface $dateTime): ?string { return $dateTime ? \Carbon\CarbonImmutable::instance($dateTime)->setTimezone(config('app.timezone'))->format('F j, Y \\a\\t g:i A') : null; }
}
