<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import ValidationSummary from '@/Components/ValidationSummary.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
const props=defineProps<{customer:any;customerUsers:any[];events:any[];canAddSecondLogin:boolean}>();
const second=useForm({name:'',email:'',password:''});
const reset=useForm({password:''});
const resetPassword=(user:any)=>{if (!window.confirm(`Reset password for ${user.name}?`)) return; reset.put(route('admin.customer-users.password.update',user.id));};
</script>
<template><Head :title="customer.name"/><AuthenticatedLayout><template #header><h2 class="text-xl font-semibold">Client: {{ customer.name }}</h2></template><div class="mx-auto max-w-5xl space-y-5 p-6">
  <section class="bg-white p-4 shadow"><h3 class="font-semibold">Client contact</h3><p>{{ customer.contact_name || 'Not provided' }}</p><p>{{ customer.email || 'No email' }} · {{ customer.phone || 'No phone' }}</p></section>
  <section class="bg-white p-4 shadow"><h3 class="font-semibold">Login accounts</h3><div v-for="user in customerUsers" :key="user.id" class="flex justify-between border-b py-3"><span><b>{{ user.name }}</b> — {{ user.email }} <span class="text-sm text-gray-500">{{ user.customer_account_role === 'primary' ? 'Primary' : user.customer_account_role === 'secondary' ? 'Secondary' : 'Existing login' }}</span></span><form @submit.prevent="resetPassword(user)" class="flex gap-2"><input v-model="reset.password" type="password" required placeholder="New password" class="rounded border-gray-300 text-sm"/><button class="text-indigo-600">Reset password</button></form></div>
    <form v-if="canAddSecondLogin" @submit.prevent="second.post(route('admin.customers.second-login.store',customer.id))" class="mt-4 grid gap-2 border-t pt-3 md:grid-cols-4"><input v-model="second.name" required placeholder="Second login name" class="rounded border-gray-300"/><input v-model="second.email" type="email" required placeholder="Email" class="rounded border-gray-300"/><input v-model="second.password" type="password" required placeholder="Temporary password" class="rounded border-gray-300"/><button class="rounded bg-indigo-600 text-white">Add second login</button><div class="md:col-span-4"><ValidationSummary :errors="second.errors"/></div></form><p v-else class="mt-3 text-sm text-gray-600">This Client already has the maximum two customer login accounts.</p></section>
  <section class="bg-white p-4 shadow"><h3 class="font-semibold">Event, capacity, and finance</h3><div v-for="event in events" :key="event.id" class="border-b py-3"><div class="flex justify-between"><b>{{ event.title || 'Invitation setup not completed' }}</b><Link :href="route('events.show',event.id)" class="text-indigo-600">Open Event</Link></div><dl class="mt-2 grid gap-2 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Invitation</dt><dd>{{ event.invitation_status }}</dd></div><div><dt class="text-gray-500">Guest capacity</dt><dd>{{ event.guest_capacity ? `${event.guest_capacity} guests` : 'Not assigned' }}</dd></div><div><dt class="text-gray-500">Package</dt><dd>{{ event.package?.name || 'No package assigned' }}</dd></div><div><dt class="text-gray-500">Price</dt><dd>{{ event.package?.price === null || event.package?.price === undefined ? 'Price not set' : `$${Number(event.package.price).toFixed(2)}` }}</dd></div></dl><p v-if="event.finance.has_record" class="mt-2 text-sm">Final {{ event.finance.final_amount }} · Paid {{ event.finance.paid_amount }} · Remaining {{ event.finance.remaining_amount }}</p><p v-else class="mt-2 text-sm text-gray-600">No financial record yet.</p></div><p v-if="!events.length" class="text-gray-600">No Events yet.</p></section>
  <Link :href="route('admin.customers.index')" class="text-indigo-600">Back to Clients</Link>
</div></AuthenticatedLayout></template>
