<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import ValidationSummary from '@/Components/ValidationSummary.vue';
import Badge from '@/Components/UI/Badge.vue';
import Button from '@/Components/UI/Button.vue';
import Card from '@/Components/UI/Card.vue';
import EmptyState from '@/Components/UI/EmptyState.vue';
import PageHeader from '@/Components/UI/PageHeader.vue';
import { invitationStatus, money, paymentStatus, statusTone } from '@/Support/AdminPresentation';
import { Head, Link, useForm } from '@inertiajs/vue3';

const props = defineProps<{ customer: any; allowance: any; customerUsers: any[]; events: any[]; canAddSecondLogin: boolean }>();
const second = useForm({ name: '', email: '', password: '' });
const allowanceForm = useForm({ allowed_events: props.allowance.allowed_events });
const reset = useForm({ password: '' });
const resetPassword = (user: any) => { if (window.confirm(`Reset password for ${user.name}?`)) reset.put(route('admin.customer-users.password.update', user.id)); };
const paymentTone = (event: any) => !event.finance?.has_record ? 'unpaid' : event.finance.remaining_amount > 0 ? (event.finance.paid_amount > 0 ? 'partially_paid' : 'unpaid') : 'paid';
</script>

<template>
  <Head :title="customer.name" />
  <AuthenticatedLayout>
    <template #header><PageHeader :title="customer.name" subtitle="Client account, invitation entitlement, and operational overview."><template #actions><Link :href="route('admin.customers.index')" class="fe-btn fe-btn-secondary">Back to Clients</Link><Link v-if="allowance.can_create_event" :href="route('events.create', { customer_id: customer.id })" class="fe-btn fe-btn-primary">Create Event</Link></template></PageHeader></template>
    <div class="fe-page fe-page-wide space-y-6">
      <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><p class="text-xs font-bold uppercase tracking-wider text-[color:var(--fe-text-muted)]">Allowed</p><p class="mt-2 text-2xl font-semibold">{{ allowance.allowed_events }}</p></Card><Card><p class="text-xs font-bold uppercase tracking-wider text-[color:var(--fe-text-muted)]">Used</p><p class="mt-2 text-2xl font-semibold">{{ allowance.used_events }}</p></Card><Card><p class="text-xs font-bold uppercase tracking-wider text-[color:var(--fe-text-muted)]">Remaining</p><p class="mt-2 text-2xl font-semibold">{{ allowance.remaining_events }}</p></Card><Card><p class="text-xs font-bold uppercase tracking-wider text-[color:var(--fe-text-muted)]">Primary login</p><p class="mt-2 break-words font-semibold">{{ customerUsers[0]?.email || 'Not assigned' }}</p></Card></section>
      <div class="grid gap-6 xl:grid-cols-3"><Card><h2 class="fe-section-title">Client information</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-[color:var(--fe-text-muted)]">Contact</dt><dd>{{ customer.contact_name || 'Not provided' }}</dd></div><div><dt class="text-[color:var(--fe-text-muted)]">Email</dt><dd class="break-words">{{ customer.email || 'No email' }}</dd></div><div><dt class="text-[color:var(--fe-text-muted)]">Phone</dt><dd>{{ customer.phone || 'No phone' }}</dd></div></dl><form class="mt-5 border-t border-[color:var(--fe-border)] pt-4" @submit.prevent="allowanceForm.put(route('admin.customers.update', customer.id))"><label class="text-sm">Allowed invitations<input v-model="allowanceForm.allowed_events" :min="allowance.used_events" type="number" required class="mt-1 w-full" /></label><ValidationSummary :errors="allowanceForm.errors" /><Button type="submit" variant="secondary" :loading="allowanceForm.processing" class="mt-3">Save allowance</Button></form><p v-if="!allowance.can_create_event" class="mt-3 text-sm text-[color:var(--fe-warning)]">Allowance is exhausted. Increase it before creating another event.</p></Card><Card class="xl:col-span-2"><h2 class="fe-section-title">Accounts</h2><div v-if="customerUsers.length" class="mt-4 divide-y divide-[color:var(--fe-border)]"><div v-for="user in customerUsers" :key="user.id" class="flex flex-wrap items-end justify-between gap-3 py-4"><div><p class="font-semibold">{{ user.name }} <span class="font-normal text-[color:var(--fe-text-muted)]">· {{ user.customer_account_role }}</span></p><p class="text-sm text-[color:var(--fe-text-secondary)]">{{ user.email }}</p></div><form class="flex flex-wrap items-end gap-2" @submit.prevent="resetPassword(user)"><label class="text-sm">Temporary password<input v-model="reset.password" type="password" required class="mt-1 w-full sm:w-52" /></label><Button type="submit" variant="secondary" :loading="reset.processing">Reset password</Button></form></div></div><EmptyState v-else class="mt-4" title="No client accounts yet." /><form v-if="canAddSecondLogin" class="mt-5 grid gap-3 border-t border-[color:var(--fe-border)] pt-5 sm:grid-cols-2 lg:grid-cols-4" @submit.prevent="second.post(route('admin.customers.second-login.store', customer.id))"><label>Name<input v-model="second.name" required class="mt-1 w-full" /></label><label>Email<input v-model="second.email" type="email" required class="mt-1 w-full" /></label><label>Temporary password<input v-model="second.password" type="password" required class="mt-1 w-full" /></label><div class="flex items-end"><Button type="submit" :loading="second.processing">Add secondary login</Button></div><ValidationSummary :errors="second.errors" class="sm:col-span-2 lg:col-span-4" /></form></Card></div>
      <Card><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="fe-section-title">Client events</h2><p class="fe-section-copy">Invitation status, capacity, RSVP progress, and finance.</p></div><span class="text-sm text-[color:var(--fe-text-muted)]">{{ events.length }} total</span></div><div v-if="events.length" class="mt-4 grid gap-4 lg:grid-cols-2"><article v-for="event in events" :key="event.id" class="rounded border border-[color:var(--fe-border)] p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-semibold">{{ event.title || 'Invitation setup' }}</h3><p class="mt-1 text-sm text-[color:var(--fe-text-secondary)]">{{ event.event_type || 'Type not set' }} · {{ event.date || 'Date not set' }}</p><div class="mt-2 flex flex-wrap gap-2"><Badge :tone="statusTone(event.invitation_status)">{{ invitationStatus(event.invitation_status) }}</Badge><Badge :tone="statusTone(paymentTone(event))">{{ paymentStatus(paymentTone(event)) }}</Badge></div></div><div class="flex gap-2"><Link :href="route('events.show', event.id)" class="fe-btn fe-btn-secondary">View</Link><Link v-if="event.invitation_status !== 'archived'" :href="route('events.builder', event.id)" class="fe-btn fe-btn-secondary">Edit</Link></div></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><dt class="text-[color:var(--fe-text-muted)]">Capacity</dt><dd>{{ event.allocated_capacity }} / {{ event.guest_capacity || '—' }}</dd></div><div><dt class="text-[color:var(--fe-text-muted)]">Families</dt><dd>{{ event.responded_families_count }} / {{ event.families_count }}</dd></div><div><dt class="text-[color:var(--fe-text-muted)]">Confirmed</dt><dd>{{ event.confirmed_attendees }}</dd></div><div><dt class="text-[color:var(--fe-text-muted)]">Outstanding</dt><dd>{{ event.finance?.has_record ? money(event.finance.remaining_amount) : '—' }}</dd></div></dl></article></div><EmptyState v-else class="mt-4" title="No events yet." message="Create an event when the client has remaining invitation allowance." /></Card>
    </div>
  </AuthenticatedLayout>
</template>
